### ISSUE TITLE
Error in parse_vector(x, col_factor(levels, ordered, include_na), na = na,  :    is.character(x) is not TRUE

### ISSUE THREAD

**Issue by avi-kluger** [ropensci/qualtRics#101]
Using getSurvey produces this error.  With a help of a programmer, we ran getSurvey with debug and found it that it is caused by readr package.  Looking into this issue, it seems to be cause by an update to reader 1.3.1.  See, 

https://github.com/tidyverse/readr/issues/921

Testing the same code on a computer in which has reader 1.1.1 the does not produce this error.

Any suggestions?  With much appreciation for the qualtRics package.

**Comment by avi-kluger** [comment]
I wrote a function that get read one Qualtrics survey at a time:
source(
"https://raw.githubusercontent.com/avi-kluger/Qualtrix/master/read_Qualtrics.R")

? read_Qualtrics

**Comment by juliasilge** [comment]
Thanks so much for your feedback! 🙌 I'd love to get to the bottom of some of these issues with `read_survey()`. If you are able, can you re-install from GitHub here, run the following code, and then email me (my address is in the DESCRIPTION file) the CSV file at the path you find? It will be a fairly raw, unprocessed CSV file, but that is the one that is causing problems, apparently!

```
root_url <- qualtRics:::append_root_url(Sys.getenv("QUALTRICS_BASE_URL"), "responseexports")
raw_payload <- qualtRics:::create_raw_payload(
    surveyID = <YOUR SURVEY ID HERE>,
    label = TRUE,
    last_response = NULL,
    start_date = NULL,
    end_date = NULL,
    unanswer_recode = NULL,
    limit = NULL,
    local_time = FALSE,
    include_questions = NULL
  )
res <- qualtRics:::qualtrics_api_request("POST", url = root_url, body = raw_payload)
ID <- res$result$id
survey.fpath <- qualtRics:::download_qualtrics_export(paste0(root_url, ID), verbose = TRUE)
survey.fpath
```

**Comment by juliasilge** [comment]
Thanks for sharing the CSV via email @avi-kluger! The CSV reads just fine so that apparently is not the problem.

I am beginning to suspect that it is a problem in the [infer_data_types() function](https://github.com/ropensci/qualtRics/blob/ffd784c110da1c5caab31264cb5a85f543131a04/R/fetch_survey.R#L207). You can see where that function is [implemented here](https://github.com/ropensci/qualtRics/blob/ffd784c110da1c5caab31264cb5a85f543131a04/R/utils.R#L397).

Are you still getting this error, after updating to the latest versions on CRAN of tidyverse and qualtRics? Can you tell me if you get the error with both or just one of the following ways of using this package?

```r
survey1 <- fetch_survey(surveyID = <YOUR SURVEY ID>, convert = TRUE)
survey2 <- fetch_survey(surveyID = <YOUR SURVEY ID>, convert = FALSE)
```

**Comment by avi-kluger** [comment]
Dear Julie,

Both commands import the file, but place the labels rather than the value of the response in the extracted file.  See example attached.

Avi

**Comment by juliasilge** [comment]
Thanks so much @avi-kluger! You can't actually attach files to a GitHub thread, but if you would like to email me the examples, you can find my address in the [DESCRIPTION](https://github.com/ropensci/qualtRics/blob/master/DESCRIPTION) file.

**Comment by juliasilge** [comment]
Today I rewrote [`infer_data_types()`](https://github.com/ropensci/qualtRics/blob/f31878cbcd97bc70e8f728e2b93a6f2b5aea9170/R/utils.R#L399) in a way that I *hope* solves this problem. 🤞 

Do you want to try installing this package from GitHub and then using `fetch_survey()` with `convert = TRUE`? You should no longer see the error.

```r
remotes::install_github("ropensci/qualtRics")
```

**Comment by avi-kluger** [comment]
Dear Julia,

I keep getting the same problem.  If you want, I can create for you a Qualtrics user on my system (I am the administrator of my School), copy the example file for your account, and let you try to read it.

Avi

**Comment by juliasilge** [comment]
@avi-kluger Hmmmm, that is surprising. Can you send me two updated files via email, if you are able? Send me the following CSV:

```r
root_url <- qualtRics:::append_root_url(Sys.getenv("QUALTRICS_BASE_URL"), "responseexports")
raw_payload <- qualtRics:::create_raw_payload(
    surveyID = <YOUR SURVEY ID HERE>,
    label = TRUE,
    last_response = NULL,
    start_date = NULL,
    end_date = NULL,
    unanswer_recode = NULL,
    limit = NULL,
    local_time = FALSE,
    include_questions = NULL
  )
res <- qualtRics:::qualtrics_api_request("POST", url = root_url, body = raw_payload)
ID <- res$result$id
survey.fpath <- qualtRics:::download_qualtrics_export(paste0(root_url, ID), verbose = TRUE)
survey.fpath
```

And then send me the following info in an RDS file:
```r
md <- tibble::enframe(metadata(surveyID =  <YOUR SURVEY ID HERE>,
                                 get = list(
                                   "questions" = TRUE,
                                   "metadata" = FALSE,
                                   "responsecounts" = FALSE))[[1]])
readr::write_rds(md, "<YOUR PATH HERE>")
```

You can't attach files to a GitHub thread but you can find my email address in the [DESCRIPTION](https://github.com/ropensci/qualtRics/blob/master/DESCRIPTION) file.

**Comment by avi-kluger** [comment]
Dear Julie,

The code fails.  Below is a copy of the code and the first error message

library('qualtRics')

Sys.setenv(QUALTRICS_API_KEY = “<my API code>”,
           QUALTRICS_BASE_URL = "az1.qualtrics.com")

root_url <- qualtRics:::append_root_url(Sys.getenv("az1.qualtrics.com"), "responseexports")
raw_payload <- qualtRics:::create_raw_payload(
  surveyID = "SV_czG0xcwKradWRyB",
  label = TRUE,
  last_response = NULL,
  start_date = NULL,
  end_date = NULL,
  unanswer_recode = NULL,
  limit = NULL,
  local_time = FALSE,
  include_questions = NULL
)
res <- qualtRics:::qualtrics_api_request("POST", url = root_url, body = raw_payload)
Error in curl::curl_fetch_memory(url, handle = handle) : <url> malformed

**Comment by juliasilge** [comment]
Wow, that is very strange because none of that code has been changed at all. Can you run that code again using [reprex](https://reprex.tidyverse.org/articles/articles/magic-reprex.html, and paste the output here on GitHub (i.e. don't reply by email)?

**Comment by avi-kluger** [comment]
![image](https://user-images.githubusercontent.com/8085952/58156041-e1a5b380-7c7d-11e9-9248-f511fed6d67c.png)

**Comment by avi-kluger** [comment]
The above runs fine with regards to Sys.setenv when I put the actual MyAPI

**Comment by juliasilge** [comment]
Well, that is good news! Just to clarify something, the reprex package puts the output onto your clipboard. You might find [this link](https://reprex.tidyverse.org/articles/articles/magic-reprex.html) helpful to show how it works.

So it looks like there is no problem with getting the survey data, if I understand your message above? I expect there is also no problem with getting the metadata. The [edit that I recently made](https://github.com/ropensci/qualtRics/commit/f31878cbcd97bc70e8f728e2b93a6f2b5aea9170) in rewriting `infer_data_types()` has solved the problem with the original error message for this issue you submitted for other users. Can you make sure you have installed this package from GitHub?

```r
devtools::install_github("ropensci/qualtRics")
```

And then try your original query once more?

```r
test_survey <- fetch_survey(surveyID = <YOUR SURVEY ID>, convert = TRUE)
```

**Comment by avi-kluger** [comment]
Here is my test.  Below is a picture of the problem persisting in the data frame "test_survey".  As you can see, instead of giving values of the question it reads the labels of each response option.
``` r
library(qualtRics)
test_survey <- fetch_survey(surveyID = "SV_czG0xcwKradWRyB", convert = TRUE)
#> 
  |                                                                       
  |                                                                 |   0%
  |                                                                       
  |=================================================================| 100%
#> Warning in infer_data_types(data, surveyID): The 'StartDate', 'EndDate' and 'RecordedDate' variables were converted without passing
#> a specific timezone. If you like to set these timestamps to your own timezone, please
#> visit https://www.qualtrics.com/support/survey-platform/getting-started/managing-your-account/
#> (under 'User Settings'). See https://api.qualtrics.com/docs/dates-and-times for more
#> information about how the Qualtrics API handles dates and times.
```

<sup>Created on 2019-05-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

![image](https://user-images.githubusercontent.com/8085952/58231190-09a91b80-7d3f-11e9-9c90-8f0754c02988.png)

**Comment by juliasilge** [comment]
Ah OK, this is helpful now. Can you describe how this is not what you are expecting? This looks to me like what we have intended to have as the output of the `fetch_survey()` function.

- The column names should match up what you have in Qualtrics as the names of each item.
- The labels/attributes on the columns should give the information for each item.
- The data in each column should be the responses from each respondent.

This is all the same as previous version of qualtRics; I haven't changed any of this functionality, other than making it work when it sometimes broke before. What here is not what you expect?

**Comment by juliasilge** [comment]
I believe this error is now fixed in the development version. File a new issue with details if you still are having problems! ✨
