### ISSUE TITLE
pkgdown website?

### ISSUE THREAD

**Issue by maelle** [ropensci/qualtRics#104]
I :eyes: a lot of activity in this repo, and that you're preparing a CRAN update. Good occasion to add an :sparkles: rOpenSci styled pkgdown website :sparkles: (and its URL to DESCRIPTION)? https://ropensci.github.io/rotemplate/#how-to-use

I can understand it's not your priority at all at the moment. :wink: Also, note that `rotemplate` and its guidance are brand-new, so any comment is welcome.

**Comment by juliasilge** [comment]
Thanks for the heads up about this @maelle! I have made a [pkgdown site](https://ropensci.github.io/qualtRics/articles/qualtRics.html) (just manually for now) and will work on getting that updating.

**Comment by maelle** [comment]
😍
