### ISSUE TITLE
fetch_survey error

### ISSUE THREAD

**Issue by dvdroney** [ropensci/qualtRics#105]
Receiving the following error when switching from getSurvey() to fetch_survey() 

Error in infer_data_types(data, surveyID)

Any ideas on what is causing this?

**Comment by juliasilge** [comment]
Thanks for the feedback! I am not seeing that error in any of my use of the package so I'm going to need a bit more detail on the kind of error you are seeing. Also, what happens if you use `convert = FALSE`?

**Comment by dvdroney** [comment]
Setting convert = FALSE seems to have fixed the issue. Thank you so much!

**Comment by dvdroney** [comment]
Hi Julia,
I just wanted to say thank you for the qualtRics package! I just came
across it last week and it has been wonderful to use. I am relatively new
to r, but this has definitely helped my day-to-day work a lot lately.
Thank you so much!
David
