### ISSUE TITLE
package qualtRics is not available for R 3.5.3 

### ISSUE THREAD

**Issue by ElenaCan** [ropensci/qualtRics#109]
Installing package into �C:/Users/elena/OneDrive/Documents/R/win-library/3.5�
(as �lib� is unspecified)
Warning in install.packages :  package ‘qualtRics’ is not available (for R version 3.5.3)
 Show Traceback
Error in library(qualtRics) : there is no package called ‘qualtRics’

**Comment by juliasilge** [comment]
Hello there @ElenaCan! You have caught this repo in the time period just between submitting to CRAN and actually being on CRAN. In the mean time, you can install via devtools or remotes:

```
install.packages("remotes")
remotes::install_github("ropensci/qualtRics")
```

**Comment by juliasilge** [comment]
We're [back on CRAN](https://cran.r-project.org/package=qualtRics)!
