### ISSUE TITLE
Getting a new warning message after last update

### ISSUE THREAD

**Issue by LarryVincent** [ropensci/qualtRics#112]
Ever since I downloaded the most recent update I've been getting a dozen or so parsing errors. The specific message is "Warning: 9 parsing failures.
 row col           expected actual                                                                              file
1032 X82 1/0/T/F/TRUE/FALSE      3 '/var/folders/sp/1w_322yx4mx4q5r843t0cmd00000gn/T//RtmpU5Ez4b/xxxxxxxxx.csv'

What does this mean?

**Comment by 11rchitwood** [comment]
Are you using `read_survey()`? That function uses `readr::read_csv()` under the hood, and the error message you pasted in looks like parsing failure output from `read_csv()`. `read_csv()` only looks at the first 1000 rows of data to guess the data type for each column. The number of rows in controlled by the `guess_max` argument, so the way to fix this would be to set `guess_max = 1032` or greater in `read_csv()`.

Currently, I don't think their is a way to pass arguments to `read_csv()` via `read_survey()`. @juliasilge, is that correct? If so, maybe there should be a separate issue for passing args through `...`.

**Comment by juliasilge** [comment]
Thanks for reporting this problem @LarryVincent! I really want to get to the bottom of this because apparently it is a problem that multiple people have had but I have not been able to repro it.

Can you run the following code and then email me (my address is in the DESCRIPTION file) the CSV file at the path you find? It will be a fairly raw, unprocessed CSV file, but that is the one that is causing problems, apparently!

```
root_url <- qualtRics:::append_root_url(Sys.getenv("QUALTRICS_BASE_URL"), "responseexports")
raw_payload <- qualtRics:::create_raw_payload(
    surveyID = <YOUR SURVEY ID HERE>,
    label = TRUE,
    last_response = NULL,
    start_date = NULL,
    end_date = NULL,
    unanswer_recode = NULL,
    limit = NULL,
    local_time = FALSE,
    include_questions = NULL
  )
res <- qualtRics:::qualtrics_api_request("POST", url = root_url, body = raw_payload)
ID <- res$result$id
survey.fpath <- qualtRics:::download_qualtrics_export(paste0(root_url, ID), verbose = TRUE)
survey.fpath
```

**Comment by juliasilge** [comment]
Today I rewrote [`infer_data_types()`](https://github.com/ropensci/qualtRics/blob/f31878cbcd97bc70e8f728e2b93a6f2b5aea9170/R/utils.R#L399) in a way that I *hope* solves this problem. 🤞 

If you are still having problems, can you try installing this package from GitHub and then using `fetch_survey()` with `convert = TRUE`? You should no longer see the error.

```r
remotes::install_github("ropensci/qualtRics")
```

**Comment by juliasilge** [comment]
I believe this error is now fixed in the development version. File a new issue with details if you still are having problems! ✨
