### ISSUE TITLE
get-survey exportColumnMap

### ISSUE THREAD

**Issue by dapbs** [ropensci/qualtRics#115]
Does the package support retrieving the current "Q to QID" mapping, as exposed on the [get-survey](https://api.qualtrics.com/reference#get-survey) endpoint under the **exportColumnMap** node?

**Comment by juliasilge** [comment]
If I understand your question correctly, yes, that mapping is available from the [`survey_questions()`](https://ropensci.github.io/qualtRics/reference/survey_questions.html) function. Give that a go and let me know if that's not what you mean. 🙌

**Comment by dapbs** [comment]
Thanks @juliasilge! My two cents: [survey_questions()](https://github.com/ropensci/qualtRics/blob/8b779946638abd4c2471d00b4e739fa0b4a88dfb/R/survey_questions.R) only exposes the "questions" node on the [get-survey](https://api.qualtrics.com/reference#get-survey) endpoint. My understanding is that this shows all the QIDs that are "associated" with a survey - this includes QIDs that were previously mapped to questions but are no longer part of the survey. The "exportColumnMap" node exposes the **current (or active) "Q to QID" mapping**.

**Comment by juliasilge** [comment]
Thank you for the clarification!

**Comment by juliasilge** [comment]
OK @dapbs this is now implemented in the `survey_questions()` function, because it turns out we were already getting all that info from Qualtrics when making that call, like you were pointing out. 

If you want to get the survey questions, you use the function like before:

```r
survey_questions(surveyID = my_survey_id)
```

If you want to get the column mapping, use `column_map = TRUE`:

```r
survey_questions(surveyID = my_survey_id, column_map = TRUE)
```

**Comment by juliasilge** [comment]
A new plan, actually! I will edit that previous message. I made a new function instead in commit 9c354bf0e8b4f70ad4c6535ad17b05c8e58bfe2b. You can access the column map via the new `column_map()` function:

```r
library(qualtRics)
column_map(surveyID = my_survey_id)
```
