### ISSUE TITLE
Qualtrics API raised a bad request (400) error

### ISSUE THREAD

**Issue by amehtaSF** [ropensci/qualtRics#117]
Got this error with the call 
`ema_df = fetch_survey(surveyID = qualtrics_survey_id, 
                      verbose = TRUE, 
                      force_request = TRUE, 
                      convert = FALSE,
                      local_time = FALSE,
                      convertVariables = FALSE,
                      dateWarning = FALSE,
                      unanswer_recode = "",
                      label = TRUE)
`
It appears that the addition of the `unanswer_recode` parameter is the cause. Error message requested that I report...

**Comment by juliasilge** [comment]
Thanks @amehtaSF for this report! I was able to reproduce the problem with `unanswer_recode = ""`, which apparently is not a value the API can handle for recoding questions that were seen but not answered. I've added some error checking so it now gives a more useful message.

You can use lots of options such as a space (`" "`) or a null value (the default, `NULL`) for recoding these kinds of answers, but not an empty string.
