### ISSUE TITLE
registerOptions() still runs on pkg load if .qualtRics.yml present

### ISSUE THREAD

**Issue by monicathieu** [ropensci/qualtRics#118]
Hi (again) @juliasilge,

In setting up the newer package on another machine of mine, I noticed a funky thing happening. It looks like you've deprecated `registerOptions()` in lieu of having those settings be args to `fetch_survey()` (I like this new format!). However, it appears that [`.onLoad()` still calls `registerOptions()` if there is a config file in the working directory](https://github.com/ropensci/qualtRics/blob/d419bc668f77f1cd41f9246025043eba8f550754/R/zzz.R#L10), which might then override any args specified in `fetch_survey()`.

On this machine of mine, I had a `.qualtRics.yml` config file saved in my working directory, from the pre-2018 version of the pacakge. In my particular case, I discovered the `registerOptions()` auto-run thing because `fetch_survey()` was constantly behaving as if `label = FALSE` even though I'd set it as `TRUE`. Deleting `qualtRics.yml` solved the problem on package reload.

This problem will only apply to users who had a config file setup with a pre-2018 version of the package, so in the long run that's not that many people, but I wanted to flag this in case you want to change the `.onLoad` behavior. THANK YOU as always!

**Comment by juliasilge** [comment]
Thanks so much @monicathieu! 🙌 

I was gradually deprecating (first a warning, etc, for users who are learning the new functionality) but you are right that this behavior is unexpected. I have changed `registerOptions()` to truly being deprecated now and have removed the `.onLoad()` behavior in commit 9c354bf0e8b4f70ad4c6535ad17b05c8e58bfe2b.
