### ISSUE TITLE
Update/improve testing

### ISSUE THREAD

**Issue by juliasilge** [ropensci/qualtRics#120]
Look into using [vcr](https://github.com/ropensci/vcr) for testing API calls.

**Comment by juliasilge** [comment]
rOpenSci has a [resource here on using vcr, webmockr, etc for testing](https://books.ropensci.org/http-testing/).

**Comment by shaun-jacks** [comment]
I could look into this, currently liking the idea of using webmockr and adding tests for behavior on different stubbed response codes

**Comment by juliasilge** [comment]
I would definitely love help in moving the existing tests over to this more modern framework, and making sure that the main user-facing functions are adequately tested. 🙏

**Comment by juliasilge** [comment]
Closed in #140
