### ISSUE TITLE
Open text question responses displaying as 'NA'

### ISSUE THREAD

**Issue by Kcappel** [ropensci/qualtRics#122]
The survey we are pulling contains a open text question that was added four months after the survey was created. When reviewing the dataset, I noticed that all the responses for this question are all valued as 'NA'. It is my understanding that when a call is made qualtRics will read a certain number of rows in a column and assign a type to the column based on the number of rows it read. Because there is four months of missing data, qualtRics assigns a boolean type to the column causing any responses made after the four month period to be removed and replaced with NA values. Is there a solution to mitigate this?

**Comment by juliasilge** [comment]
Just so I know for future work, did this problem get solved for you @Kcappel using qualtRics, or did you go about this a different way?

**Comment by Kcappel** [comment]
This was solved using qualtRics. I ended up creating a second dataframe to hold responses that started on a certain date and stitched that data together with the full survey list.

**Comment by juliasilge** [comment]
OK, thanks for the update. I think I need to change some things about how parsing is handled to make it more robust; others have reported problems, such as in #119.
