### ISSUE TITLE
Error: Unauthorized (HTTP 401)

### ISSUE THREAD

**Issue by emmacooperpeterson** [ropensci/qualtRics#126]
I'm not sure if this is a Qualtrics issue or something I'm doing wrong, but I get an error when I try any command from this package. I am able to manually call the Qualtrics API outside of this package, so I am fairly certain my API token is correct.

After updating my .Renviron and restarting R, I get this:
```
surveys()

Error in request("GET", key = key, api_url = page_url) : 
  Unauthorized (HTTP 401).
```

I checked similar issues with no success. Do you know of any reason aside from an invalid API token that this might happen?

Thank you!

**Comment by juliasilge** [comment]
Thanks so much for your patience on this! 🙌 

Can you run the following code and share what happens?

```
root_url <- qualtRics:::append_root_url(Sys.getenv("QUALTRICS_BASE_URL"), "surveys")
qualtRics:::qualtrics_api_request("GET", root_url)
```

If it is possible you to share what the result of `root_url` is, that could also be helpful.

Also, you won't be able to share the results entirely because it involves your key, but can you tell me what happens if you run the following?

```
qualtRics:::construct_header(Sys.getenv("QUALTRICS_API_KEY"))
```

**Comment by emmacooperpeterson** [comment]
Aha, I just misread the `base_url` description! Ours is `companyname.co1.qualtrics.com` and I originally thought just `companyname.co1` was my base_url and I assumed `.qualtrics.com` was getting added to it somewhere. I added `.qualtrics.com` and it now works!

Thanks for the response! Checking the result of `root_url` is how I realized what the issue was 🎉

**Comment by juliasilge** [comment]
Ah, fantastic! ✨  Let me know if you have any other problems.
