### ISSUE TITLE
let fetch_survey() fail gently when there aren't any responses

### ISSUE THREAD

**Issue by kevintroy** [ropensci/qualtRics#127]
If you fetch_survey() and there aren't any responses in the survey you're calling for, the API call will return a dataset with just the header rows, but the embedded call to read_survey() will fail because of this line:

`assertthat::assert_that(nrow(rawdata) > 0, msg = "The survey you are trying to import has no responses.")`

That's fine if you're just fetching a single survey, but what if you're trying to process all the responses that came in last month, across many surveys?

`all_surveys() %>% `
  `filter(isActive) %>% `
  `pull(id) %>% `
  `map(fetch_survey, start_date = start_of_prior_month, end_date = end_of_prior_month)`

One bad apple will spoil the bunch:  downloads will stop as soon as read_survey consumes its first empty survey, and any data that has been successfully read up to that point will be discarded.

Seems like this could be fixed by either changing read_survey() to allow it to return a tibble with 0 rows (i.e. change the hard assert above to a warning message), or having fetch survey() do a try/except sort of thingy when it calls read_survey().

**Comment by juliasilge** [comment]
Hello there @kevintroy! 👋 

A previous user has brought this up in #92 and and #93, but the proposed solution there isn't what I would like to see. 

The really best option is to set up your iteration using `map()` so that it passes through [purrr::safely](https://r4ds.had.co.nz/iteration.html#dealing-with-failure). The purrr package has "adverbs" especially for such situations.

I did in #93 talk about possibly changing the behavior to return a warning instead of an error, perhaps with a zero-row data frame.

**Comment by kevintroy** [comment]
Thx, @juliasilge!  I agree that returning text (per #93) isn't a good solution -- functions that return tibbles shouldn't sometimes return something else.  

For the same reason, I'm not a big fan of safely() for this -- it returns tibbles for surveys with responses and NULL values for those without.  And those are within a list structure that needs to be unpacked first.  So, there's some contortions required to get to a plain 'ole list of tibbles that we can map dplyr verbs to without the NULLs breaking stuff:

`vector_of_survey_ids %>%`
`safely(map(fetch_survey)) %>%`
`lapply("[[", "result") %>%` 
`keep(function(x) {! is.null(x)})`

That certainly works, and it's only two more lines of code, but it doesn't feel very smooth or intuitive, versus having fetch_survey return a row-less tibble.

**Comment by juliasilge** [comment]
OK, I believe I have this implemented now. We should now get a zero-row dataframe when reading or fetching empty surveys. When there is no data, we can't do much checking or converting of data types, so it will always return all columns as character. I've checked this out on a couple of surveys i have with no data in them and it looks good to me. ✅ 

Check it out @kevintroy and let me know if you see any problems! 🙏

**Comment by kevintroy** [comment]
Looks good to me, thx @juliasilge!
