### ISSUE TITLE
maybe don't .Rbuildignore NEWS.md ?

### ISSUE THREAD

**Issue by sckott** [ropensci/qualtRics#129]
if you remove this line https://github.com/ropensci/qualtRics/blob/master/.Rbuildignore#L20 then NEWS will show up on the CRAN page for this pkg (e.g., like your tidytext pkg). Or maybe there's a reason you don't want it to show up on CRAN?

**Comment by juliasilge** [comment]
I... have no idea why that was ignored. 🤷🏻‍♀️ It predates my time as maintainer of this package. Thanks for the heads up!

**Comment by sckott** [comment]
right, figured just leftover from before since you didn't have that in tidytext, thanks!
