### ISSUE TITLE
Include questions labels in fetch_survey tibble

### ISSUE THREAD

**Issue by jstevens5** [ropensci/qualtRics#132]
Along the same lines as issue #116 and #35, is it possible to include question labels as the primary labels for the tibbles when importing from `fetch_survey()` and `read_survey()`? Currently, they are listed as secondary labels, but they cannot be used to refer to the appropriate columns (e.g, `select()` cannot find columns based on the question labels). 
I have used `colnames(datafile) <- sjlabelled::get_label(datafile)` as a workaround, but it would be nice to have the option at import to use question labels as column names. This is especially useful when researchers have added labels in Qualtrics, so the labels rather than the questions are included.

**Comment by juliasilge** [comment]
There is also discussion of labels in #134; seems like there is some work to do to get to a better set of ways to handle the labels, question names, etc.

**Comment by chrisumphlett** [comment]
see my comment in #134

**Comment by chrisumphlett** [comment]
And I'll add - what @jstevens5 wants to do is what I wanted to do, though in the end I liked getting the labels as data first, because then I could edit those labels into a clean and truncated form before pivoting out as a column name. If you were going to make this an option directly you'll need to make decisions (or parameterize) the naming convention. The labels can be super long

**Comment by juliasilge** [comment]
We made some changes in #199 so the question labels are more accessible in the `fetch_survey() tibble output, as an attribute:

``` r
library(qualtRics)
res <- fetch_survey("SV_5BJxxxx")
#>   |                                                                              |                                                                      |   0%  |                                                                              |=========================================================             |  82%  |                                                                              |======================================================================| 100%
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   .default = col_character(),
#>   StartDate = col_datetime(format = ""),
#>   EndDate = col_datetime(format = ""),
#>   Progress = col_double(),
#>   `Duration (in seconds)` = col_double(),
#>   Finished = col_logical(),
#>   RecordedDate = col_datetime(format = ""),
#>   RecipientLastName = col_logical(),
#>   RecipientFirstName = col_logical(),
#>   RecipientEmail = col_logical(),
#>   ExternalReference = col_logical(),
#>   LocationLatitude = col_double(),
#>   LocationLongitude = col_double(),
#>   Q1007 = col_double(),
#>   Q1_DO_1 = col_double(),
#>   Q1_DO_2 = col_double(),
#>   Q1_DO_3 = col_double(),
#>   Q1_DO_4 = col_double(),
#>   Q1_DO_5 = col_double(),
#>   SolutionRevision = col_double(),
#>   FL_6_DO_FL_7 = col_double()
#>   # ... with 4 more columns
#> )
#> ℹ Use `spec()` for the full column specifications.
attr(res, "column_map")
#> # A tibble: 46 x 7
#>    qname        description      main        sub   ImportId    timeZone choiceId
#>    <chr>        <chr>            <chr>       <chr> <chr>       <chr>    <chr>   
#>  1 StartDate    Start Date       Start Date  ""    startDate   Z        <NA>    
#>  2 EndDate      End Date         End Date    ""    endDate     Z        <NA>    
#>  3 Status       Response Type    Response T… ""    status      <NA>     <NA>    
#>  4 IPAddress    IP Address       IP Address  ""    ipAddress   <NA>     <NA>    
#>  5 Progress     Progress         Progress    ""    progress    <NA>     <NA>    
#>  6 Duration (i… Duration (in se… Duration (… ""    duration    <NA>     <NA>    
#>  7 Finished     Finished         Finished    ""    finished    <NA>     <NA>    
#>  8 RecordedDate Recorded Date    Recorded D… ""    recordedDa… Z        <NA>    
#>  9 ResponseId   Response ID      Response ID ""    _recordId   <NA>     <NA>    
#> 10 RecipientLa… Recipient Last … Recipient … ""    recipientL… <NA>     <NA>    
#> # … with 36 more rows
```

<sup>Created on 2021-01-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

The mapping from question label to column is not quite general enough for us in this package to be able to always know how to translate a question label into a column name (for example, Qualtrics matrix questions) so we aren't going to support the feature request described here fully, but we hope that the changes made may make this process more fluent in your workflow.
