### ISSUE TITLE
fetch_survey does not pulled edited responses

### ISSUE THREAD

**Issue by patrick-k-krause** [ropensci/qualtRics#133]
Hi, I am having where survey responses that have been edited post-completion (by the research team using the qualtrics web browser) are not being reflected in the API export using the fetch_survey() command. 

When I use the qualtrics API directly it returns the edited values, but the fetch_survey() export returns the original value for the question and not the edited value. In the documentation i have not found an existing argument for the fetch_survey command that will return the edited values.

**Comment by bbherbert** [comment]
I too experience this issue. I have fetch_survey(force_request = TRUE). Only upon "retaking" the survey does the edited response load.  

Looking forward to a fix!

**Comment by juliasilge** [comment]
We have just updated to the most updated API that Qualtrics uses in #135. Can you install this package from GitHub and see if this problem is now fixed?

**Comment by chrisumphlett** [comment]
I am seeing edited data fwiw in the new version. In this case, where we have removed a respondent's PII (it comes through as NA when I `fetch_survey`)

**Comment by juliasilge** [comment]
Fantastic! I am going to close this issue; if someone has a problem with this in the future, please open a new issue.
