### ISSUE TITLE
Survey questions with html do not correctly `infer_data_types`

### ISSUE THREAD

**Issue by NickLarsen** [ropensci/qualtRics#138]
When you download the survey data as a csv, all html is stripped from the responses on single answer multiple choice questions.  However, when you download the survey metadata during the `infer_data_types` function, the original question text comes back including the html.  The result is that the levels contain html but the responses do not, so you end up with parsing warnings for each response that includes one of the html containing options.

This eliminates all of those values from the `fetch_survey` results.  They end up as `NA`s.

**Comment by juliasilge** [comment]
Hello @NickLarsen! 👋 

Some of this code predates my work on this package but let's see what we can figure out. I believe the [only HTML stripping that happens in this package itself](https://github.com/ropensci/qualtRics/blob/f6eb9a3cfd9f89f8bf645b30d86c57366c73cd23/R/read_survey.R#L125) is of the **labels** (not column names, not entries in columns, but attributes on columns). When `infer_data_types()` gets these labels, it [takes them off](https://github.com/ropensci/qualtRics/blob/f6eb9a3cfd9f89f8bf645b30d86c57366c73cd23/R/utils.R#L478), attempts to figure out what kind of data is in each column, and then puts the labels back on.

Can you give me some more information about what kind of columns are ending up as all `NA`? Is it multiple choice (not multiple select) questions with HTML _in the answer choices_? Or in the question text?

**Comment by NickLarsen** [comment]
The only example we have is a multiple choice where you can choose only 1 answer (radio buttons) and yes only in the cases where the html is in the answer choices.  Only about half the answer choices in my example contain html, and any respondent who chose one of those ends up being null, whereas the choices from the same question without html survive the `infer_data_types` function.

After you hit the `infer_data_types` function, you can do a `levels(my_data$my_field)` and see the html that's expected by the factor.  When I download the csv manually from the website, or when I download the data using the qualtRics package, the actual response values do not contain the html.

I'm not entirely sure what the best path going forward is, but for the time being we worked around this by fetching with `convert=FALSE` then selecting out that question, calling `infer_data_types` on the rest of the data, then adding that field back in after manually creating the factor for it.  Our data is converted to tidy format later on so the levels themselves are not particularly important for further analysis but I just wanted to note that this was happening.

**Comment by juliasilge** [comment]
I have made [an example survey](https://conjoint.qualtrics.com/jfe/form/SV_3gbwq8aJgqPwQDP) that contains some TRULY STUPENDOUS HTML in the answer choices. Hopefully I can get a handful of people to take the survey (@NickLarsen??? Anybody else have a few spare minutes to check out the awesome HTML I made?) and get a bit of test data to figure out what is going on here.

Anybody who stops by this issue, [please take the survey](https://conjoint.qualtrics.com/jfe/form/SV_3gbwq8aJgqPwQDP)! 🙏  It's short!!!

**Comment by 11rchitwood** [comment]
I took it, but you also may want to [generate some test responses](https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/generating-test-responses/).

**Comment by juliasilge** [comment]
Well, that's convenient! Although none of the test responses say "This is the way". 😝 

I can confirm that I see the `NA` values for the responses that have HTML in the answer choices.

**Comment by juliasilge** [comment]
You were right @NickLarsen; it was `infer_data_types()` and the factor levels.

Should be fixed now, from the test data I can see. Thanks for the report! 🙌

**Comment by NickLarsen** [comment]
Hooray! thanks!
