### ISSUE TITLE
Install Version 3.1.2

### ISSUE THREAD

**Issue by kgilds** [ropensci/qualtRics#142]
Is there a way to install version 3.1.2. When I installed the development version, I still get version 3.1.1. 

Curious if I am missing a step when I install from github or if I just have to wait. 

Thanks

**Comment by 11rchitwood** [comment]
Have you tried `remotes::install_github("ropensci/qualtRics", force = TRUE)`?

**Comment by juliasilge** [comment]
If you install from GitHub as @11rchitwood demonstrates, you should see something like:

```
qualtRics   * 3.1.1.900 2020-02-20 [1] Github (ropensci/qualtRics@f6eb9a3)
```
 in the output of `devtools::session_info()`. That is the most up-to-date version as 3.1.2 is WIP right now. I do plan to release to CRAN very soon. 

Let us know if that is not working! 🙌
