### ISSUE TITLE
not importing scored data

### ISSUE THREAD

**Issue by devtomlinson** [ropensci/qualtRics#143]
my fetch_survey is not importing scored data

**Comment by juliasilge** [comment]
Thanks for the report @devtomlinson! 🙌 Can you give me a bit more detail about what "scored data" is? Can you share a public version of a survey that uses this, or example data, or a link to documentation from Qualtrics about it?

**Comment by devtomlinson** [comment]
Sure! Here's a link to their website about scoring: https://www.qualtrics.com/support/survey-platform/survey-module/survey-tools/scoring/. Basically, I have outputs from questionnaires coded in the scoring, but I am not able to see them in the output.

**Comment by devtomlinson** [comment]
I actually figured something out - it is importing the scored data, but the column names are not what I have them set to be. They are being set as "SC0", "SC1", etc.

**Comment by juliasilge** [comment]
Ah yes, that makes sense. We discussed similar issues in #121; this is how the scored data gets exported by Qualtrics. 👍
