### ISSUE TITLE
Replacing deprecated getLegacyResponseData with fetch_survey

### ISSUE THREAD

**Issue by ergundel** [ropensci/qualtRics#149]
Hello,

This question seems rudimentary, but I can't see what I'm doing wrong. I'm trying to update an old R script that pulls in survey data in R (using getLegacyResponseData) into the newer version of the Qualtric API.

From what I can see in the documentation, the following should pull the survey data into the variable x:

> require(qualtRics)
> qualtrics_api_credentials( api_key="lWxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", base_url="https://xxxxxx.qualtrics.com",install=TRUE)   
> readRenviron("~/.Renviron")
> x=fetch_survey( surveyID="SV_xxxxxxxxxxxxxxx")  

 
On the last line, I get the following error message:

> Error in qualtrics_response_codes(res) : 
>   Qualtrics API raised a bad request (400) error - Please report this on
> https://github.com/ropensci/qualtRics/issues

Any idea what I might be doing wrong?

**Comment by juliasilge** [comment]
What happens if you do this?

```r
all_surveys()
```

Do you see a dataframe of the surveys you have access to in your org?

**Comment by ergundel** [comment]
Yes, I can see all of the projects in my group

**Comment by juliasilge** [comment]
Well, that means your credentials are being set correctly. 👍 

Can you:
a) reinstall from CRAN
```r
install.packages("qualtRics")
```
b) run the following code using [reprex](https://github.com/tidyverse/reprex), to make sure that nothing weird is happening environment-wise? Paste you get here for us if you still get an error.

```r
library(qualtRics)
my_survey <- "PUTYOURIDHERE"
fetch_survey(my_survey)
```

**Comment by juliasilge** [comment]
Let us know if you have more problems!
