### ISSUE TITLE
Qualtrics API raised a bad request (400) error

### ISSUE THREAD

**Issue by shiney3** [ropensci/qualtRics#154]
I am now getting this error message when I execute a fetch_survey request: 
Error in qualtrics_response_codes(res) : 
  Qualtrics API raised a bad request (400) error

Using 'getSurvey' runs without issues, other than a message stating that is deprecated, and to use fetch_survey. 

Please advise. 

Windows 10
R ver.: 3.6.3

**Comment by juliasilge** [comment]
Hello there @shiney3!

To get started solving this problem, can you please look at how to build and run a [reprex](https://www.tidyverse.org/help/)? If you haven't ever used this tool, [this article explains it](https://reprex.tidyverse.org/articles/articles/magic-reprex.html) in detail. Can you run the following code in a reprex to confirm that your credentials are set up correctly?

``` r
library(qualtRics)
all_surveys()
#> # A tibble: 3 x 6
#>   id         name           ownerId     lastModified    creationDate    isActive
#>   <chr>      <chr>          <chr>       <chr>           <chr>           <lgl>   
#> 1 SV_3gbwq8… Beskar Armor   UR_8wfG5qs… 2020-02-20T01:… 2020-02-20T00:… TRUE    
#> 2 SV_56icaa… Cats Can Have… UR_8wfG5qs… 2020-02-11T04:… 2020-02-11T03:… TRUE    
#> 3 SV_5BJRo2… Sourdough Bre… UR_8wfG5qs… 2020-03-29T20:… 2020-03-29T20:… TRUE
```

<sup>Created on 2020-04-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Your output should look similar to mine, but with **your** surveys. If anything sensitive prints out, please just censor them in the output after pasting using XXXX or similar.

**Comment by juliasilge** [comment]
I'm going to close this for now @shiney3. Let us know if you continue to have problems! 🙌
