### ISSUE TITLE
fetch_survey colnames does not use question export tags

### ISSUE THREAD

**Issue by seanchrismurphy** [ropensci/qualtRics#157]
Latest version of fetch_survey returns dataframes that do not correctly apply question export tags, at least for Matrix items. Default numbering (e.g. _1, _2, _3) is being used instead. This is breaking integration with extensions I've been making around the questions API point, which do return with question export tags.

**Comment by seanchrismurphy** [comment]
Update: This seems to only be happening for particular matrix question blocks.. currently trying to figure out what differentiates these from the ones that seem to have the question export tags retrieved appropriately. Nothing obvious standing out yet.

**Comment by 11rchitwood** [comment]
I have experienced this as well. Been waiting to put together a repress before submitting this issue.

**Comment by jmobrien** [comment]
Can't speak to your specific scenario, but I'm dealing with this a bit for myself right now.  Quite possibly has to do with current dev state of this packace, where `fetch_survey` is on the most current v3 endpoint, but `questions` is on the older (beta v3) endpoint.

Also, a possibly related thing you might want to check that could help: I believe older API versions would continue to rename things if renamings had been set in "recodings" web menu, but later unchecked.  Current fetch won't do that--but I believe you'll still see renamings in the older question endpoints, which might be the source of the mismatch.  

I think even in the older metadata there's a flag for whether it's checked, though--something to guide your search, perhaps?

**Comment by dsen6644** [comment]
@seanchrismurphy Do you have the ability to export the survey as a csv using the Qualtrics UI? If so, do you still see column headers with `_1`, `_2`, etc.?

**Comment by seanchrismurphy** [comment]
@dsen6644 Yes I've exported the survey as a csv - the headers there match the recoded values within Qualtrics, not the `_1`, `_2` returned by this package.

**Comment by seanchrismurphy** [comment]
Just an update: I've found a workaround at the moment - the _N values on the import ids (used as headers if import_id = TRUE) match the recoding in the survey. So it is possible with some tweaking to switch to import ids in both the question endpoint and the data endpoint and have them line up.
