### ISSUE TITLE
Error in value[[3L]](cond) :    Error extracting csv from zip file. Please re-run your query.

### ISSUE THREAD

**Issue by netruh** [ropensci/qualtRics#159]
fetch_survey is throwing an error. Error in value[[3L]](cond) : Error extracting csv from zip file. Please re-run your query.

**Comment by juliasilge** [comment]
Hello there @netruh!

To get started solving this problem, can you please look at how to build and run a [reprex](https://www.tidyverse.org/help/)? If you haven't ever used this tool, [this article explains it](https://reprex.tidyverse.org/articles/articles/magic-reprex.html) in detail. Can you run the following code in a reprex to confirm that your credentials are set up correctly?

``` r
library(qualtRics)
all_surveys()
#> # A tibble: 3 x 6
#>   id         name           ownerId     lastModified    creationDate    isActive
#>   <chr>      <chr>          <chr>       <chr>           <chr>           <lgl>   
#> 1 SV_3gbwq8… Beskar Armor   UR_8wfG5qs… 2020-02-20T01:… 2020-02-20T00:… TRUE    
#> 2 SV_56icaa… Cats Can Have… UR_8wfG5qs… 2020-02-11T04:… 2020-02-11T03:… TRUE    
#> 3 SV_5BJRo2… Sourdough Bre… UR_8wfG5qs… 2020-03-29T20:… 2020-03-29T20:… TRUE
```

<sup>Created on 2020-04-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Your output should look similar to mine, but with **your** surveys. If anything sensitive prints out, please just censor them in the output after pasting using XXXX or similar.

**Comment by juliasilge** [comment]
I'm going to close this issue for now @netruh. Let us know if you continue to have problems! 🙌
