### ISSUE TITLE
Export Word Document version of survey (ugh)

### ISSUE THREAD

**Issue by jrosen48** [ropensci/qualtRics#163]
I am interested in exporting a Word Document version of a survey. This *may* be useful as a codebook: it provides the question number (which is what {qualtRics} provides by default) and text, as well as the way in which response options are coded. 

Is this available through the API?

(If not) is there a better way to achieve a similar goal?

**Comment by jrosen48** [comment]
spoke to soon - I see `metadata()` proivides this information. Wondering if it would be possible/desirable to think about parsing that into a different (tidy?) form.

**Comment by juliasilge** [comment]
You probably already know about `survey_questions()`, which provides some info on question number and question text.

You can parse out the results of `metadata()` using lots of `map()` if you want to get those values into a dataframe:

``` r
library(qualtRics)
library(tidyverse)

my_surveys <- all_surveys() %>%
  pull(id)

survey_questions(my_surveys[1])
#> # A tibble: 6 x 4
#>   qid   qname question                                                force_resp
#>   <chr> <chr> <chr>                                                   <lgl>     
#> 1 QID63 Q63   How often do you typically use your beskar armor?       TRUE      
#> 2 QID16 Q16   Overall, how satisfied are you with your beskar armor?  TRUE      
#> 3 QID17 Q17   Have you ever contacted customer service about your be… TRUE      
#> 4 QID18 Q18   Have all problems been resolved to your complete satis… FALSE     
#> 5 QID19 Q19   Why not?                                                FALSE     
#> 6 QID22 Q22   If you would like to share any additional comments or … FALSE

questions_meta <- metadata(my_surveys[1])$questions %>%
  enframe(name = "qid")

questions_meta %>%
  mutate(questionType = map(value, "questionType"),
         questionTypetype = map_chr(questionType, "type"),
         validation = map(value, "validation"), 
         validationForceResponse = map_lgl(validation, "doesForceResponse"))
#> # A tibble: 6 x 6
#>   qid   value     questionType   questionTypetype validation  validationForceRe…
#>   <chr> <list>    <list>         <chr>            <list>      <lgl>             
#> 1 QID63 <named l… <named list [… MC               <named lis… TRUE              
#> 2 QID16 <named l… <named list [… MC               <named lis… TRUE              
#> 3 QID17 <named l… <named list [… MC               <named lis… TRUE              
#> 4 QID18 <named l… <named list [… MC               <named lis… FALSE             
#> 5 QID19 <named l… <named list [… TE               <named lis… FALSE             
#> 6 QID22 <named l… <named list [… TE               <named lis… FALSE
```

<sup>Created on 2020-05-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jmobrien** [comment]
@jrosen48 I'm wondering if `column_map()` might be a better fit for this goal?  That only includes the variables that are in the participant response download, while (I believe) `survey_questions()` provides everything.

FYI--currently there's an API endpoint version mismatch for the metadata (inc. column mapping) vs. fetch functions.  Fetch has been updated to the current v3 endpoint, while the others are a work in progress.  Things generally still work together, but it's possible you might see a few inconsistencies.

**Comment by juliasilge** [comment]
Let us know if you have further questions on this @jrosen48! 🙌

**Comment by jrosen48** [comment]
Thanks all!
