### ISSUE TITLE
Basic Question-error when using Base URL

### ISSUE THREAD

**Issue by GabriellaS-K** [ropensci/qualtRics#164]
Hi! 

Thanks for this brilliant package! I am fairly new with R, so please forgive a pretty basic question! 

I keep encountering the same error message: 
```

Error: The Qualtrics base URL must end with '.qualtrics.com'. Your base URL looks like this: '<https://anthropology.eu.qualtrics.com>'.
Please visit https://api.qualtrics.com/docs/root-url for instructions about the Qualtrics base URL.

```

My code is below (I'm using R markdown, and have put in random numbers for my API Key for now)

```{r}
library(qualtRics)

qualtrics_api_credentials(api_key = "<1234567890>",
                          base_url = "<https://anthropology.eu.qualtrics.com>",
                          install = TRUE, overwrite = TRUE)

```

Then, I try to see my surveys: 

```{r}
readRenviron("~/.Renviron")
surveys <- all_surveys()
```
And that is where I get the error message!

Thanks to anyone that can help

**Comment by GabriellaS-K** [comment]
fixed by removing the <> around the API and URL and generating a new API!!

**Comment by juliasilge** [comment]
Glad you figured it out! 🎉
