### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by GabriellaS-K** [ropensci/qualtRics#166]
Hi, 

Me again-sorry! This is certainly me being new to R and the qualtRics package, but I am finding the same error message: 

`Error in parse_url(url) : length(url) == 1 is not TRUE

Below is my code, the API has been put in with random numbers :) 

Can someone explain what the error message is saying? 

`---
title: "Study 1 Demographic Data"
author: "Gabriella"
date: "12/05/2020"
output:
  pdf_document: default
  html_document: default
---
# Aims of this script
This script is a record of how I imported my survey data from the Qualtrics survey-How do you experience your premenstrual phase? 
The aim of this survey is to gather data and records of how people experience the premenstrual phase, in order to build a tool to measure PMS. 

# The structure of this script

To be filled in 

```{r setup, include=FALSE}
#Not 100% sure why this code works and what it does...?
knitr::opts_chunk$set(echo = TRUE)
```

### Install qualtRics from CRAN

```{r packages} 

# install qualtRics package if not installed yet
if (!require(qualtRics)) install.packages('qualtRics') 

#If package is installed:
library(qualtRics)

#If already installed the qualtRics package, put this at the start of chunk (not sure why...[link](https://stackoverflow.com/questions/29189663/trying-to-publish-an-r-notebook-and-keep-getting-the-same-error-error-in-contri/29190024))
chooseCRANmirror(graphics=FALSE, ind=1)


```

### Get Qualtrics Survey Data by pulling data from Qualtrics

__Registering Qualtrics credentials__  
Two important credentials needed to authenticate with the Qualtrics API. These are: 

    
* API key 
* Institution-specific base URL. 
    + The base URL should either look like yourdatacenterid.qualtrics.com or like yourorganizationid.yourdatacenterid.qualtrics.com. 

Store  API credentials QUALTRICS_API_KEY and QUALTRICS_BASE_URL in the .Renviron file for repeated use across sessions. The qualtRics package has a function to help with this.

_Making code/API secret, [explained here](https://cran.r-project.org/web/packages/httr/vignettes/secrets.html)_

```{r importing_data}
# For this I am using the [website](https://docs.ropensci.org/qualtRics/


library(qualtRics)

#Inserting qualtrics credentials to allow it to pull the answers. 
#The 'overwrite' function allows you to input a different key and re-run this, overwriting what was stored. 
#The 'install=True' function saves the API key in the Renviron file, 
qualtrics_api_credentials(api_key = "1234567890",
                          base_url = "dfsghscniuyeky.eu.qualtrics.com",
                          install = TRUE, overwrite = TRUE)

#After using this function, reload environment to be able to use the credentials without restarting R.
readRenviron("~/.Renviron")

#Once I have the ability to pull qualtrics data into R, I need to choose the survey to pull:

#First, show all the surveys, which will appear in the data environment
surveys <- all_surveys()

#Select the survey needed for this (CAPTURING THE DIVERSITY OF PREMENSTRUAL EXPERIENCES), the ID is [3] This function downloads a survey from Qualtrics and imports it into R. 
mysurvey <- fetch_survey(surveyID = surveys$id[3],
                         verbose = TRUE, force_request = TRUE, convert=FALSE)
```

### Looking at the Survey results 

```{r checkingdata}
#retrieves a data frame containing questions and question IDs for a survey.

survey_questions(mysurvey) 
# retrieves metadata about your survey, such as questions, survey flow, number of responses etc.
metadata(mysurvey)
```

Sorry, and thanks for your help!

` #

**Comment by juliasilge** [comment]
One thing that might help you is to [read a bit more about R Markdown](https://rmarkdown.rstudio.com/), for example to understand what the first chunk does. Another resource that I think might help you is the [STAT 545 website](https://stat545.com/) that is focused on workflow and how to use R.

Here are a couple of notes:

- You do *not* want to install packages from within your `.Rmd`. Do that outside of your script, in your console.
- You probably do not want to install your API credentials in your `.Rmd`. Instead, write these to your `.Renviron` interactively and then use them all the time from there.
- You do *not* need to read your `.Renviron` file in the `.Rmd` because that happens at the beginning of a new R session automatically. You only need to do this after you _change_ the `.Renviron`.

Code in your `.Rmd` could look something like this:

```r
library(qualtRics)

## choose the survey you need from `all_surveys()`
survey_id <- "SV_XXXXXX"

pms_raw <- fetch_survey(survey_id,
                        verbose = TRUE, force_request = TRUE, convert=FALSE)

survey_questions(survey_id)
metadata(survey_id)
```

**Comment by GabriellaS-K** [comment]
That is again, super helpful. Will read these both before continuing with the code. Thank you for your patience!

**Comment by juliasilge** [comment]
No problem at all! 💪 

Another good place to ask questions is [RStudio Community](https://community.rstudio.com/); there are lots of helpful people there ready to answer R-related questions.
