### ISSUE TITLE
suggestion: change the content added to "label" attribute

### ISSUE THREAD

**Issue by jmobrien** [ropensci/qualtRics#168]
Right now, `read_survey()` contains a section that generate the labels from the second row of the raw downloaded response CSV, which contains a Qualtrics-constructed description of the item content.  There's some text-matching that tries to pull out the part of the second row cell believed to be most likely meaningful, but it's got some problems, and I'm thinking it might be worth just removing.  

Biggest concern is that it can lead to meaningless and ambiguous labels.  For instance, two multiple choice questions "Do you have a favorite cheese? {Yes, it's [text box entry] / No}" and "Do you live in the United States {Yes / No, I live in [text box entry]}" would both produce 2 vars: one for the choice, and one for anything written in the text box.  

Although the description cell for each variable would be different, the label-generation code would just pull out 2 identical end parts for each question's variables: "Selected Choice", and "Text Entry", with results that are then ambiguous.  Also, even if there was only one of the two items in the survey, the label still doesn't make clear what the item actually is.  I've been encountering both annoyances lot lately while trying to match variables across multiple long surveys. I eventually just gave up on our labels and pulled out the second row data myself.  

(There are sometimes other problems, too, because the code is really just implementing some heuristics built around where hyphens are found in the description cell, and it's not always perfect.)

There's clearly some thought put into this section, and I could see it making sense for certain use cases, e.g. where individual choices have clear labels, but the overall prompts are too long to be a useful label.  Still, with problems even with simple questions like MC + text box, I suspect most users will more often see the drawbacks.  I'm wondering maybe if it should be left in, but change the default behavior to use the entire cell for label-generation.

**Comment by juliasilge** [comment]
Related to #132.

I would love to see some more discussion around this. I will be honest that I **never** use those labels and do not find them useful; the code to create those labels predates my work on this package. In my opinion, it is more useful to have the question text and other info in another dataframe and use joins to get that information back to the correct columns for specific analysis work.

Personally I would be pretty happy to see the labels go aways but I am not sure how folks are depending on those labels and what a good way to serve that need might be.

**Comment by jmobrien** [comment]
Also related to #146, then, specifically [here](https://github.com/ropensci/qualtRics/pull/146#issuecomment-614717880).  Question text could go in the column maps, and I tend to think it should regardless of what we decide here.

Until recently, I had no personal opinion about question text as attributes. But now I'm actually using them: I'm building R-native datasets that can also be exported as Stata .dat files, including the label metadata.  That seems to be the primary purpose of the functionality in sjlabelled, and why the attribute is called a "label".  So, I'm now glad the labels are there, just annoyed at the places where text truncation isn't helping.

Also, for larger datasets with many potential users, I'm realizing that attributes can be a good place to store question text--mainly b/c it can help users get more analysis done w/fewer stops to check codebooks.  Of course, that doesn't mean THIS package must add them in up front, vs. people who want them doing joins as you say. Still, I know plenty of researchers who can analyze a lot better than they can data-wrangle, so for them maybe  might be a nice touch.   

But I do think we should probably at least pull all this out of `read_survey()` into its own utility, then figure out what we really want it to do, and with what defaults.

**Comment by lyh970817** [comment]
I'm trying to put together a package that makes more comprehensive use of the metadata to generate variable dictionaries and add label attributes to survey data variables. For now I think the label content I have does uniquely identifies a variable in the exported data set - so some parts of it might be relevant https://github.com/lyh970817/qualtdict.

**Comment by juliasilge** [comment]
Closed in #199 with the column mapping and metadata functionality 👍
