### ISSUE TITLE
Not able to access the survey 

### ISSUE THREAD

**Issue by hsinfei** [ropensci/qualtRics#172]
I have my account and I have access to a survey build under another school's domain. In this case, the fetch_survey does not allow me access the survey that's build under another schools' domain and gives me this message "Error in qualtrics_response_codes(res) : 
  Qualtrics API raised a bad request (400) error - Please report this on
https://github.com/ropensci/qualtRics/issues"

**Comment by juliasilge** [comment]
I'm sorry you're having trouble! Have you used `qualtrics_api_credentials()` with `install = TRUE` to install your credentials to your `.Renviron` file? Once you think you have that set up, try running this using [reprex](https://www.tidyverse.org/help/) so we can diagnose any problems.

```r
library(qualtRics)
all_surveys()
```

If that works (i.e. you can see the surveys you should have access to), what happens if you try this with the survey ID, again using reprex?

```r
library(qualtRics)
fetch_survey(surveyID = "SV_XXX") ## put your ID here
```

**Comment by hsinfei** [comment]
Thanks for your reply. Everything works and after the fetch_survey(surveyID = "SV_XXX") ## put your ID here, it shows "The survey you are importing has no responses." However, there are at least 350 responses if I check it on the website. Any suggestions will be appreciated.

The following is an example:
qualtrics_api_credentials(api_key = "my_api", 
                          base_url = "myschool.co1.qualtrics.com",
                          install = TRUE,overwrite=TRUE)

readRenviron("~/.Renviron")
surveys <- all_surveys() 
# 5,14-16
CS <- fetch_survey(surveyID = surveys$id[5], verbose = TRUE, label = FALSE,
                    unanswer_recode = -2,convert = FALSE, force_request=TRUE)
The other survey I try to download is build under another school's domain. If I use the method you suggest, then I will get zero reponses.

I have tried to change the base_url:
qualtrics_api_credentials(api_key = "my api", 
                          base_url = "anotherschool.qualtrics.com",
                          install = TRUE,overwrite=TRUE)
readRenviron("~/.Renviron")
CI <- fetch_survey(surveyID = surveys$id[14], verbose = TRUE, label = FALSE,
                    unanswer_recode = -2,convert = FALSE, force_request=TRUE)

Then the error message is:
Error in qualtrics_response_codes(res) : 
  Qualtrics API raised a bad request (400) error - Please report this on
https://github.com/ropensci/qualtRics/issues

**Comment by juliasilge** [comment]
To dig into this problem, we need you to use reprex so we can make sure the environment is clean, etc. If you haven't used reprex before, check out [this article on it](https://reprex.tidyverse.org/articles/articles/magic-reprex.html). After you have that set up, try running this code:

```r
library(qualtRics)
all_surveys()
```

If that works (i.e. you can see the surveys you should have access to), what happens if you try this with the survey ID, again using [reprex](https://reprex.tidyverse.org/index.html)?

```r
library(qualtRics)
fetch_survey(surveyID = "SV_XXX") ## put your ID here

**Comment by hsinfei** [comment]
``` r
library(qualtRics)
qualtrics_api_credentials(api_key = "myapi", 
                          base_url = "school1.co1.qualtrics.com",
                          install = TRUE,overwrite=TRUE)
#> Your original .Renviron will be backed up and stored in your R HOME directory if needed.
#> Your Qualtrics key and base URL have been stored in your .Renviron.  
#> To use now, restart R or run `readRenviron("~/.Renviron")`

readRenviron("~/.Renviron")
surveys <- all_surveys() 
# 5,14-16
CS <- fetch_survey(surveyID = surveys$id[5], verbose = TRUE, label = FALSE,
                    unanswer_recode = -2,convert = FALSE, force_request=TRUE)
#>   |                                                                              |                                                                      |   0%  |                                                                              |==============                                                        |  20%  |                                                                              |============================                                          |  41%  |                                                                              |================================                                      |  46%  |                                                                              |==============================================                        |  66%  |                                                                              |============================================================          |  86%  |                                                                              |======================================================================| 100%
#> Parsed with column specification:
#> cols(
#>   .default = col_double(),
#>   StartDate = col_datetime(format = ""),
#>   EndDate = col_datetime(format = ""),
#>   RecordedDate = col_datetime(format = ""),
#>   ResponseId = col_character(),
#>   DistributionChannel = col_character(),
#>   UserLanguage = col_character(),
#>   Q1_5_TEXT = col_character(),
#>   Q10_12_TEXT = col_character(),
#>   Q11_12_TEXT = col_character(),
#>   Q13_15_TEXT = col_character(),
#>   Q20 = col_character(),
#>   Q17 = col_character(),
#>   Q22 = col_character(),
#>   Q25 = col_character(),
#>   Q29_6_TEXT = col_character(),
#>   Q45_5_TEXT = col_character(),
#>   Q46_15_TEXT = col_character(),
#>   Q49 = col_character(),
#>   Q51_13_TEXT = col_character(),
#>   Q220_10_TEXT = col_character()
#>   # ... with 23 more columns
#> )
#> See spec(...) for full column specifications.
CI <- fetch_survey(surveyID = surveys$id[14], verbose = TRUE, label = FALSE,
                   unanswer_recode = -2,convert = FALSE, force_request=TRUE)
#>   |                                                                              |                                                                      |   0%  |                                                                              |======================================================================| 100%
#> The survey you are importing has no responses.

qualtrics_api_credentials(api_key = "myapi", 
                          base_url = "school2.qualtrics.com",
                          install = TRUE,overwrite=TRUE)
#> Your original .Renviron will be backed up and stored in your R HOME directory if needed.
#> Your Qualtrics key and base URL have been stored in your .Renviron.  
#> To use now, restart R or run `readRenviron("~/.Renviron")`
readRenviron("~/.Renviron")
CI <- fetch_survey(surveyID = surveys$id[14], verbose = TRUE, label = FALSE,
                    unanswer_recode = -2,convert = FALSE, force_request=TRUE)
#> Error in qualtrics_response_codes(res): Qualtrics API raised a bad request (400) error - Please report this on
#> https://github.com/ropensci/qualtRics/issues
```

<sup>Created on 2020-06-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by juliasilge** [comment]
OK, so you are working with two Qualtrics accounts, with two different API keys and two different base URLs? In that case, it's probably less helpful to write them to `.Renviron` at all but instead to keep them in code (although that is of course less secure and you could get around this by defining custom environment variables). But for now, let's not worry about `.Renviron` at all. Only put the credentials in your environment for the single R session:

```r
library(reprex)
## use your school2 API, but do not install
qualtrics_api_credentials(api_key = "your_school2_api", 
                          base_url = "school2.qualtrics.com")

fetch_survey(surveyID = "SV_XXX", force_request=TRUE)
```
You are using a different API key for the two schools, correct? They are not the same for different accounts.

**Comment by hsinfei** [comment]
I am working with 4 Qualtrics surveys with one API and two base_url. I can access the survey build under other school's domain using my account and the my school's base_url but the qualtRics return 0 responses. Any feedbacks will be really appreciated.

**Comment by juliasilge** [comment]
I do not believe it is possible to have the same API key for two base URLs. If your API key is associated with your first account and base URL, you will only be able to use it to access surveys from that base URL. You will need to set up a separate API key for the second base URL.

**Comment by juliasilge** [comment]
Let us know if you have further questions, and good luck @hsinfei! 🙌

**Comment by hsinfei** [comment]
Thanks so much!!! @juliasilge

**Comment by hsinfei** [comment]
> Let us know if you have further questions, and good luck @hsinfei! 🙌

Hi @juliasilge , do you know if how to fix the "The survey you are importing has no responses." issue? Because I can definitely see the responses online but not using this package. Thanks!

**Comment by juliasilge** [comment]
Have you double-checked that you have an API key specifically for the base URL of _that_ survey? You will need two separate API keys, one for each base URL. One way to check that you have access is to load the authentication credentials and then look at the output of `all_surveys()`; if things are set up correctly, you will see the survey you are interested in there:

```r
library(qualtRics)
qualtrics_api_credentials(api_key = "your_api_key_here",
                          base_url = "your_url_here")
all_surveys()
```
