### ISSUE TITLE
If two questions have same name, responses in one of questions do not export

### ISSUE THREAD

**Issue by chrisumphlett** [ropensci/qualtRics#176]
Within my organization we occasionally have questions with the same "name" (I don't know what the technical term for this should be). I am referring to the value circled here: https://www.screencast.com/t/kGnFPjo6i

This may be automatically assigned by Qualtrics, and can be "auto renumbered", but can also just be whatever a user sets. Due to users copy and pasting questions we end up with the same question "name" in a survey.

Today someone discovered that all of the exported responses (using `fetch_survey`) for a particular question were NA. It was the first of two questions with the same name. I was able to fix it by changing the name of one of the questions and redoing the export.

If the user exports directly from Qualtrics the responses are there. I don't know if this is a bug in the  R package, or something with Qualtrics, but thought I'd start here. If nothing else you might be able to help me determine the best way to describe the issue to them, and consider documenting it here as well so that others know.

**Comment by juliasilge** [comment]
To start with, those names are what the package puts in the **column names**, so there is no way that R is going to be able to handle actual duplicates in those names super well. When something like `read_csv()` reads in a CSV file with duplicate column names, it appends something to make unique column names.

I do think the `NA` values are probably coming from the qualtRics package; I changed one of my test surveys to have duplicate names and there are parsing problems:

``` r
library(qualtRics)

## notice the duplicate qnames for Q3.13
survey_questions("SV_56icaa9YAafpAqx")
#> # A tibble: 13 x 4
#>    qid    qname question                                              force_resp
#>    <chr>  <chr> <chr>                                                 <lgl>     
#>  1 QID3   Q1.1  "<div>Activity Name: <b>Have a little salami... TOGE… FALSE     
#>  2 QID101 Q14   "Click to write the question text"                    FALSE     
#>  3 QID1   Q1.2  "<div><div>On which team do you currently work?</div… TRUE      
#>  4 QID2   Q2.1  "<div><div>For how long have you worked at Delicious… TRUE      
#>  5 QID18  Q3.13 "On a scale from 0-10, how likely are you to recomme… TRUE      
#>  6 QID9   Q3.13 "How much did you enjoy when we as cats had a little… TRUE      
#>  7 QID27  Q3.3  "Why did you enjoy it?"                               FALSE     
#>  8 QID28  Q3.4  "Why didn't you enjoy it?"                            FALSE     
#>  9 QID30  Q3.7  "Did having a little salami help you to be more effe… TRUE      
#> 10 QID34  Q3.8  "Please explain your answer."                         FALSE     
#> 11 QID37  Q37   "<div>Did having a little salami help you to feel mo… TRUE      
#> 12 QID36  Q35   "<div>Which of these activities would you be most in… TRUE      
#> 13 QID21  Q4.1  "How do you identify?"                                TRUE

fetch_survey("SV_56icaa9YAafpAqx", force_request = TRUE)
#>   |                                                                              |                                                                      |   0%  |                                                                              |======================================================================| 100%
#> Parsed with column specification:
#> cols(
#>   .default = col_character(),
#>   StartDate = col_datetime(format = ""),
#>   EndDate = col_datetime(format = ""),
#>   Progress = col_double(),
#>   `Duration (in seconds)` = col_double(),
#>   Finished = col_logical(),
#>   RecordedDate = col_datetime(format = ""),
#>   Q1.2_10_TEXT = col_logical(),
#>   Q3.13 = col_double(),
#>   SolutionRevision = col_double(),
#>   `Q3.8 - Parent Topics` = col_logical(),
#>   `Q3.8 - Sentiment Polarity` = col_double(),
#>   `Q3.8 - Sentiment Score` = col_double(),
#>   `Q3.8 - Topic Sentiment Label` = col_logical(),
#>   `Q3.8 - Topic Sentiment Score` = col_logical()
#> )
#> See spec(...) for full column specifications.
#> Warning: 14 parsing failures.
#> row col           expected actual
#>   1  -- value in level set     9 
#>   2  -- value in level set     10
#>   3  -- value in level set     10
#>   4  -- value in level set     10
#>   5  -- value in level set     0 
#> ... ... .................. ......
#> See problems(...) for more details.
#> # A tibble: 17 x 34
#>    StartDate           EndDate             Status Progress `Duration (in s…
#>    <dttm>              <dttm>              <chr>     <dbl>            <dbl>
#>  1 2020-02-11 03:44:39 2020-02-11 03:45:47 Surve…      100               67
#>  2 2020-02-11 04:08:16 2020-02-11 04:10:29 IP Ad…      100              133
#>  3 2020-02-11 04:08:21 2020-02-11 04:11:09 IP Ad…      100              168
#>  4 2020-02-11 04:25:59 2020-02-11 04:28:17 IP Ad…      100              137
#>  5 2020-02-11 05:18:29 2020-02-11 05:20:17 IP Ad…      100              107
#>  6 2020-02-11 05:57:47 2020-02-11 06:00:17 IP Ad…      100              149
#>  7 2020-02-11 06:39:05 2020-02-11 06:41:48 IP Ad…      100              163
#>  8 2020-02-11 06:46:53 2020-02-11 06:48:56 IP Ad…      100              122
#>  9 2020-02-11 10:30:40 2020-02-11 10:33:49 IP Ad…      100              188
#> 10 2020-02-11 13:15:40 2020-02-11 13:17:36 IP Ad…      100              115
#> 11 2020-02-12 00:59:38 2020-02-12 01:01:13 IP Ad…      100               94
#> 12 2020-02-13 16:41:14 2020-02-13 16:46:31 IP Ad…      100              316
#> 13 2020-02-13 23:24:36 2020-02-13 23:27:25 IP Ad…      100              168
#> 14 2020-02-11 04:05:27 2020-02-11 04:07:16 IP Ad…       15              108
#> 15 2020-02-13 16:24:45 2020-02-13 16:25:09 IP Ad…       15               24
#> 16 2020-02-24 21:08:13 2020-02-24 21:09:22 IP Ad…      100               68
#> 17 2020-03-04 22:35:48 2020-03-04 22:36:12 IP Ad…       15               23
#> # … with 29 more variables: Finished <lgl>, RecordedDate <dttm>,
#> #   ResponseId <chr>, DistributionChannel <chr>, UserLanguage <chr>,
#> #   Q1.2 <ord>, Q1.2_10_TEXT <lgl>, Q2.1 <ord>, Q3.13_NPS_GROUP <chr>,
#> #   Q3.13 <ord>, Q3.13_1 <chr>, Q3.3 <chr>, Q3.4 <chr>, Q3.7 <ord>, Q3.8 <chr>,
#> #   Q37 <ord>, Q35_1 <chr>, Q35_2 <chr>, Q35_7 <chr>, Q35_7_TEXT <chr>,
#> #   Q4.1 <ord>, SolutionRevision <dbl>, `Q3.8 - Parent Topics` <lgl>, `Q3.8 -
#> #   Sentiment Polarity` <dbl>, `Q3.8 - Sentiment Score` <dbl>, `Q3.8 -
#> #   Sentiment` <chr>, `Q3.8 - Topic Sentiment Label` <lgl>, `Q3.8 - Topic
#> #   Sentiment Score` <lgl>, `Q3.8 - Topics` <chr>
```

<sup>Created on 2020-06-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

The parsing problems happen because R reads the data into memory and cannot have duplicate column names, so it changes the column name. This means it no longer matches the `qname`. When qualtRics then tries to do some of the automatic type conversions, it cannot match up the columns in memory to the right metadata for the survey, because they no longer match. The conversion fails and you get `NA` values.

I definitely recommend having unique question names in your survey, because so much of how qualtRics works depends on matching that metadata up. There is some related discussion in #168 and similar about labels, qids, qnames, and how best to handle all of that.

You can avoid the type conversion that causes the `NA` values by using `convert = FALSE` in the call to `fetch_survey()`. You will not lose the values this way, but you **will** have column names that do not match up to other survey metadata.

**Comment by chrisumphlett** [comment]
Thanks. I think `convert = FALSE` would be a suitable workaround for me. I recommend having unique question names too! Alas, we have some survey setup debt.
If this happened, would end up with `Q22.1` and `Q22.2` or something like that?

**Comment by juliasilge** [comment]
If you have two questions named `Q22` and use `convert = FALSE`, I believe in most situations you will end up with `Q22` and `Q22_1`.
