### ISSUE TITLE
Error in all_surveys()

### ISSUE THREAD

**Issue by GabriellaSpence** [ropensci/qualtRics#179]
I recently updated my version of R from 3.6.2 to 4.0.1. In my previous version all_surveys() ran without error, but now it returns:

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: https

**Comment by juliasilge** [comment]
Check out #173 and #177, and be sure your base URL is saved correctly as specified in the docs.

Notice that [when you register your credentials](https://docs.ropensci.org/qualtRics/#register-your-qualtrics-credentials):

> The base URL you pass to the qualtRics package should either look like `yourdatacenterid.qualtrics.com` or like `yourorganizationid.yourdatacenterid.qualtrics.com`

**Comment by GabriellaSpence** [comment]
Ah, sorry yes this solved my issue thank you!

**Comment by juliasilge** [comment]
Excellent! 🚀
