### ISSUE TITLE
all_surveys issue 

### ISSUE THREAD

**Issue by nkraus2** [ropensci/qualtRics#183]
Hello, 

I have been having trouble when looking to request all surveys after registering my API token and base URL for our Qualtrics Data. The error appears to be with the curl function. I have updated all packages including the QualtRics package several times. Since the getSurveys function was deprecated, I have run into this issue and have been unable to use this package to download data. 

`Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: https`

**Comment by juliasilge** [comment]
Check out #173, #177, and #179, and be sure your base URL is saved correctly as specified in the docs.

Notice that [when you register your credentials](https://docs.ropensci.org/qualtRics/#register-your-qualtrics-credentials):

> The base URL you pass to the qualtRics package should either look like `yourdatacenterid.qualtrics.com` or like `yourorganizationid.yourdatacenterid.qualtrics.com`,  without a scheme such as `https://`

**Comment by juliasilge** [comment]
Let us know if you continue to have problems! 🙌
