### ISSUE TITLE
Certificate warning on https://docs.ropensci.org when browsing package documentation

### ISSUE THREAD

**Issue by mskyttner** [ropensci/qualtRics#188]
The site for the pkgdown documentation at for example https://docs.ropensci.org/qualtRics/ has a certificate that doesn't have a Subject Alt Name for docs.ropensci.org, which may cause these warnings to display in common web browsers:

![qualtRics-doc-site-screenshot-chromium](https://user-images.githubusercontent.com/1715840/93857545-07e8c280-fcbb-11ea-89af-63a0ce5b99f0.png)
![qualtRics-doc-site-screenshot-firefox](https://user-images.githubusercontent.com/1715840/93857549-0919ef80-fcbb-11ea-9828-e06f8858652d.png)

Maybe this can be useful for troubleshooting:

https://docs.github.com/en/github/working-with-github-pages/troubleshooting-custom-domains-and-github-pages

This issue seem to affect all package documentation at https://docs.ropensci.org. The content gets served without https but not when using https/SSL/TLS, for example:

http://docs.ropensci.org/qualtRics/ (works)
https://docs.ropensci.org/qualtRics/ (gives a warning)

**Comment by juliasilge** [comment]
This will be fixed soon, hopefully later today! The rOpenSci folks need to update something in their domain management.

**Comment by juliasilge** [comment]
This is fixed now! 👍
