### ISSUE TITLE
Using qualtRics to write surveys?

### ISSUE THREAD

**Issue by johnhenrypezzuto** [ropensci/qualtRics#189]
I was wondering if `qualtRics` had any features or planned features to be able to _write Qualtrics surveys_ in the future. I think this would be a useful feature because it would be often surveys follow general structure and a tool like `qualtRics` would allow many people to edit questions en masse.

If not, I was wondering if there were any other resources you could guide me towards. Offhand, I was able to find [qualtricsR](https://github.com/saberry/qualtricsR)

**Comment by juliasilge** [comment]
We don't currently have any functionality to do this, but it has been brought up before by other folks. I opened issue #106 to collect people's input and thoughts, so if you have specific input or experience, please chime in there! 🙌
