### ISSUE TITLE
Error in qualtrics_response_codes

### ISSUE THREAD

**Issue by Rkol8** [ropensci/qualtRics#193]
Error in qualtrics_response_codes(res) : 
  Qualtrics API raised a bad request (400) error - Please report this on
https://github.com/ropensci/qualtRics/issues

Code:
utd_kc <- fetch_survey(surveyID = "xxxxxxxx", force_request = TRUE, 
                       include_questions =  c("StartDate",	"EndDate",	"Status","NPS_NPS_GROUP","NPS")) %>% as_tibble()

**Comment by juliasilge** [comment]
Check out #173, #177, #179, and #184, and be sure your base URL is saved correctly as specified in the docs.

Notice that [when you register your credentials](https://docs.ropensci.org/qualtRics/#register-your-qualtrics-credentials):

> The base URL you pass to the qualtRics package should either look like `yourdatacenterid.qualtrics.com` or like `yourorganizationid.yourdatacenterid.qualtrics.com`,  without a scheme such as `https://`
