### ISSUE TITLE
fetch_survey @para label not working

### ISSUE THREAD

**Issue by fangdaxing** [ropensci/qualtRics#204]
It seems like that fetch_survey@para `label` is not working - always exports survey response as `Choice TEXT` regardless the argument `TURE/FALSE`.

**Comment by juliasilge** [comment]
Can you create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) for this? The goal of a reprex is to make it easier for us to recreate your problem so that we can understand it and/or fix it.

If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. You may already have reprex installed (it comes with the tidyverse package), but if not you can install it with:

```r
install.packages("reprex")
```

When you paste the output from reprex, you can censor out any PII or survey IDs using `XXX`. Thanks! 🙌

**Comment by juliasilge** [comment]
Let us know if you continue to have problems!

**Comment by fangdaxing** [comment]
rm(list = ls())

library(qualtRics)
library(codebook)
#> 
#> Attaching package: 'codebook'
#> The following object is masked from 'package:qualtRics':
#> 
#>     metadata
library(reprex)


qualtrics_api_credentials(
  api_key = "XXXXXXXXX",
  base_url = "XXXXXXXX",
  install = TRUE,
  overwrite = TRUE
)
#> Your original .Renviron will be backed up and stored in your R HOME directory if needed.
#> Your Qualtrics key and base URL have been stored in your .Renviron.  
#> To use now, restart R or run `readRenviron("~/.Renviron")`
readRenviron("~/.Renviron")
mysurvey1 <- fetch_survey(
  "XXXXXXXX",
 
  **lable = FALSE,**
 
  force_request = TRUE

)
#>   |                                                                              |                                                                      |   0%  |                                                                              |=========================                                             |  36%  |                                                                              |======================================================================| 100%
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   .default = col_character(),
#>   StartDate = col_datetime(format = ""),
#>   EndDate = col_datetime(format = ""),
#>   Progress = col_double(),
#>   `Duration (in seconds)` = col_double(),
#>   Finished = col_logical(),
#>   RecordedDate = col_datetime(format = ""),
#>   RecipientLastName = col_logical(),
#>   RecipientFirstName = col_logical(),
#>   LocationLatitude = col_double(),
#>   LocationLongitude = col_double(),
#>   SeekHelp_9 = col_logical(),
#>   SeekHelp_9_TEXT = col_logical(),
#>   VigPAHrs = col_double(),
#>   VigPAMins = col_double(),
#>   ModPAHrs = col_double(),
#>   ModPAMins = col_double(),
#>   Sports_1 = col_logical(),
#>   ScreenHrs = col_double(),
#>   ScreenMins = col_double(),
#>   SitTravelHrs = col_double()
#>   # ... with 7 more columns
#> )
#> ℹ Use `spec()` for the full column specifications.
#> Warning: 29 parsing failures.
#> row col           expected         actual
#>   2  -- value in level set Sometimes true
#>   5  -- value in level set Sometimes true
#>  16  -- value in level set Sometimes true
#>  32  -- value in level set Sometimes true
#>  37  -- value in level set Sometimes true
#> ... ... .................. ..............
#> See problems(...) for more details.
#> Warning: 44 parsing failures.
#> row col           expected         actual
#>   5  -- value in level set Sometimes true
#>  16  -- value in level set Sometimes true
#>  18  -- value in level set Sometimes true
#>  20  -- value in level set Sometimes true
#>  25  -- value in level set Sometimes true
#> ... ... .................. ..............
#> See problems(...) for more details.

**Comment by fangdaxing** [comment]
Thank you so much Julia for getting back to me. I'm quite new to GitHub and R. Really admire your work! I'm looking forward to learning more from you as well!

**Comment by fangdaxing** [comment]
The issue is the `label` parameter in `fetch_survey()`, regardless I put `FALSE` or `TRUE`, it always returns text response. I was expecting when I change the argument to `FALSE`, it will return numeric value under each response variable.

**Comment by juliasilge** [comment]
In order to not convert or label, you'll need to use both `label = FALSE` _and_ `convert = FALSE`:

``` r
library(qualtRics)
library(tidyverse)

fetch_survey("SV_56icaa9YAafpAqx", force_request = TRUE) %>%
  select(Q1.2)
#>   |                                                                              |                                                                      |   0%  |                                                                              |======================================================================| 100%
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   .default = col_character(),
#>   StartDate = col_datetime(format = ""),
#>   EndDate = col_datetime(format = ""),
#>   Progress = col_double(),
#>   `Duration (in seconds)` = col_double(),
#>   Finished = col_logical(),
#>   RecordedDate = col_datetime(format = ""),
#>   Q1.2_10_TEXT = col_logical(),
#>   Q3.13 = col_double(),
#>   SolutionRevision = col_double(),
#>   `Q3.8 - Parent Topics` = col_logical(),
#>   `Q3.8 - Sentiment Polarity` = col_double(),
#>   `Q3.8 - Sentiment Score` = col_double(),
#>   `Q3.8 - Topic Sentiment Label` = col_logical(),
#>   `Q3.8 - Topic Sentiment Score` = col_logical()
#> )
#> ℹ Use `spec()` for the full column specifications.
#> # A tibble: 17 x 1
#>    Q1.2                  
#>    <ord>                 
#>  1 Litter Box Maintenance
#>  2 Litter Box Maintenance
#>  3 Litter Box Maintenance
#>  4 Litter Box Maintenance
#>  5 Litter Box Maintenance
#>  6 Executive             
#>  7 Litter Box Maintenance
#>  8 Litter Box Maintenance
#>  9 Human Resources       
#> 10 Litter Box Maintenance
#> 11 Other                 
#> 12 Litter Box Maintenance
#> 13 Litter Box Maintenance
#> 14 <NA>                  
#> 15 <NA>                  
#> 16 Litter Box Maintenance
#> 17 <NA>

fetch_survey("SV_56icaa9YAafpAqx", label = FALSE, convert = FALSE, force_request = TRUE) %>%
  select(Q1.2)
#>   |                                                                              |                                                                      |   0%  |                                                                              |======================================================================| 100%
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   .default = col_double(),
#>   StartDate = col_datetime(format = ""),
#>   EndDate = col_datetime(format = ""),
#>   RecordedDate = col_datetime(format = ""),
#>   ResponseId = col_character(),
#>   DistributionChannel = col_character(),
#>   UserLanguage = col_character(),
#>   Q1.2_10_TEXT = col_logical(),
#>   Q3.3 = col_character(),
#>   Q3.4 = col_character(),
#>   Q3.8 = col_character(),
#>   Q35_7_TEXT = col_character(),
#>   `Q3.8 - Parent Topics` = col_logical(),
#>   `Q3.8 - Sentiment` = col_character(),
#>   `Q3.8 - Topic Sentiment Label` = col_logical(),
#>   `Q3.8 - Topic Sentiment Score` = col_logical(),
#>   `Q3.8 - Topics` = col_character()
#> )
#> ℹ Use `spec()` for the full column specifications.
#> # A tibble: 17 x 1
#>     Q1.2
#>    <dbl>
#>  1     4
#>  2     4
#>  3     4
#>  4     4
#>  5     4
#>  6     8
#>  7     4
#>  8     4
#>  9     9
#> 10     4
#> 11    10
#> 12     4
#> 13     4
#> 14    NA
#> 15    NA
#> 16     4
#> 17    NA
```

<sup>Created on 2021-04-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by fangdaxing** [comment]
Thank you so much!

**Comment by fangdaxing** [comment]
Hi Julia, I use both `label` and `convert` as **FALSE**, but still it returns TEXT choice data.

rm(list = ls())

library(qualtRics)
library(reprex)

qualtrics_api_credentials(
  api_key = "xxxxxxx",
  base_url = "xxxxxxx",
  install = TRUE,
  overwrite = TRUE
)
#> Your original .Renviron will be backed up and stored in your R HOME directory if needed.
#> Your Qualtrics key and base URL have been stored in your .Renviron.  
#> To use now, restart R or run `readRenviron("~/.Renviron")`
readRenviron("~/.Renviron")
mysurvey1 <- fetch_survey(
  "SV_08QUvQ8zdbZnmlf",
 
  lable = FALSE,
  convert = FALSE,
  force_request = TRUE

)
#>   |                                                                              |                                                                      |   0%  |                                                                              |=========================                                             |  36%  |                                                                              |===================================================                   |  73%  |                                                                              |======================================================================| 100%
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   .default = col_character(),
#>   StartDate = col_datetime(format = ""),
#>   EndDate = col_datetime(format = ""),
#>   Progress = col_double(),
#>   `Duration (in seconds)` = col_double(),
#>   Finished = col_logical(),
#>   RecordedDate = col_datetime(format = ""),
#>   RecipientLastName = col_logical(),
#>   RecipientFirstName = col_logical(),
#>   LocationLatitude = col_double(),
#>   LocationLongitude = col_double(),
#>   SeekHelp_9 = col_logical(),
#>   SeekHelp_9_TEXT = col_logical(),
#>   VigPAHrs = col_double(),
#>   VigPAMins = col_double(),
#>   ModPAHrs = col_double(),
#>   ModPAMins = col_double(),
#>   Sports_1 = col_logical(),
#>   ScreenHrs = col_double(),
#>   ScreenMins = col_double(),
#>   SitTravelHrs = col_double()
#>   # ... with 7 more columns
#> )
#> ℹ Use `spec()` for the full column specifications.

**Comment by juliasilge** [comment]
Can you take a look at using reprex to share your results? If you haven't used reprex before, take a [look at this article](https://www.njtierney.com/post/2017/01/11/magic-reprex/). Using a reprex makes it easier for other people to see and understand your code and results.

> Can you create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) for this? The goal of a reprex is to make it easier for us to recreate your problem so that we can understand it and/or fix it.
> 
> If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. You may already have reprex installed (it comes with the tidyverse package), but if not you can install it with:
> 
> ```r
> install.packages("reprex")
> ```
> 
> When you paste the output from reprex, you can censor out any PII or survey IDs using `XXX`. Thanks! 🙌

**Comment by fangdaxing** [comment]
Thanks very much Julia, and my apologies, just figure out how to use `reprex`

``` r
library(qualtRics)
library(reprex)
library(tidyverse)

qualtrics_api_credentials(
  api_key = "xxxxxxxxxxxx",
  base_url = "xxxxxxxxxxx",
  install = TRUE,
  overwrite = TRUE
)
#> Your original .Renviron will be backed up and stored in your R HOME directory if needed.
#> Your Qualtrics key and base URL have been stored in your .Renviron.  
#> To use now, restart R or run `readRenviron("~/.Renviron")`
readRenviron("~/.Renviron")
mysurvey1 <- fetch_survey(
  "XXXXXXXXX",
 
  lable = FALSE,
  convert = FALSE,
  force_request = TRUE

)%>%select(Climate_1)
#>   |                                                                              |                                                                      |   0%  |                                                                              |=========================                                             |  36%  |                                                                              |===================================================                   |  73%  |                                                                              |======================================================================| 100%
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   .default = col_character(),
#>   StartDate = col_datetime(format = ""),
#>   EndDate = col_datetime(format = ""),
#>   Progress = col_double(),
#>   `Duration (in seconds)` = col_double(),
#>   Finished = col_logical(),
#>   RecordedDate = col_datetime(format = ""),
#>   RecipientLastName = col_logical(),
#>   RecipientFirstName = col_logical(),
#>   LocationLatitude = col_double(),
#>   LocationLongitude = col_double(),
#>   SeekHelp_9 = col_logical(),
#>   SeekHelp_9_TEXT = col_logical(),
#>   VigPAHrs = col_double(),
#>   VigPAMins = col_double(),
#>   ModPAHrs = col_double(),
#>   ModPAMins = col_double(),
#>   Sports_1 = col_logical(),
#>   ScreenHrs = col_double(),
#>   ScreenMins = col_double(),
#>   SitTravelHrs = col_double()
#>   # ... with 7 more columns
#> )
#> ℹ Use `spec()` for the full column specifications.

mysurvey1
#> # A tibble: 275 x 1
#>    Climate_1        
#>    <chr>            
#>  1 Agree            
#>  2 Somewhat disagree
#>  3 Disagree         
#>  4 Strongly agree   
#>  5 Somewhat disagree
#>  6 Agree            
#>  7 Agree            
#>  8 Somewhat agree   
#>  9 Strongly agree   
#> 10 Agree            
#> # … with 265 more rows
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by juliasilge** [comment]
Can you try it with `label = FALSE` instead of `lable = FALSE`?

**Comment by fangdaxing** [comment]
I must be blind... 

Thank you for taking time to look at this. Much appreciated.

**Comment by juliasilge** [comment]
Happens to the best of us, like all the time!! If you have further problems or questions, do please open a new issue, with a reprex if possible. 🙌
