### ISSUE TITLE
Qualtrics API raised a bad request (400) error 

### ISSUE THREAD

**Issue by avi-kluger** [ropensci/qualtRics#205]
I get this error when trying to read a Qualtrics survey that has java loops and 8485 columns.

**Comment by juliasilge** [comment]
Is this possibly the same issue as #173, #177, #179, #184, and #193? Be sure your base URL is saved correctly as specified in the docs.

Notice that [when you register your credentials](https://docs.ropensci.org/qualtRics/#register-your-qualtrics-credentials):

> The base URL you pass to the qualtRics package should either look like `yourdatacenterid.qualtrics.com` or like `yourorganizationid.yourdatacenterid.qualtrics.com`,  without a scheme such as `https://`

**Comment by avi-kluger** [comment]
`readRenviron("~/.Renviron")
library(qualtRics)
all_surveys()

# Test fetch_survey with a survey with one column
x <- fetch_survey(surveyID = "SV_5yCKfCffhAMvjXE", force_request = TRUE)
names(x)

# Test fetch_survey with problem survey with > 8,000 columns
x <- fetch_survey(surveyID = "SV_0e8PaZwHzTsTzZX", force_request = TRUE)
names(x)

# Test the the survey has columns
survey_questions("SV_0e8PaZwHzTsTzZX")`

**Comment by avi-kluger** [comment]
all_surveys()
# A tibble: 3 x 6
  id               name                                  ownerId          lastModified       creationDate       isActive
  <chr>            <chr>                                 <chr>            <chr>              <chr>              <lgl>   
1 SV_0e8PaZwHzTsT~ Listening and performance meta-analy~ URH_afQZAKstmsD~ 2021-02-07T23:00:~ 2021-01-13T10:42:~ TRUE    
2 SV_5yCKfCffhAMv~ test4Julia                            UR_3xeCMp9bIKSP~ 2021-02-08T08:47:~ 2021-02-08T08:47:~ TRUE    
3 SV_cTONwLb7xXvk~ Test                                  UR_3xeCMp9bIKSP~ 2021-02-06T20:44:~ 2021-02-06T20:42:~ FALSE   
> 
> # Test fetch_survey with a survey with one column
> x <- fetch_survey(surveyID = "SV_5yCKfCffhAMvjXE", force_request = TRUE)
  |==============================================================================================================| 100%

-- Column specification ------------------------------------------------------------------------------------------------
cols(
  StartDate = col_datetime(format = ""),
  EndDate = col_datetime(format = ""),
  Status = col_character(),
  IPAddress = col_logical(),
  Progress = col_double(),
  `Duration (in seconds)` = col_double(),
  Finished = col_logical(),
  RecordedDate = col_datetime(format = ""),
  ResponseId = col_character(),
  RecipientLastName = col_logical(),
  RecipientFirstName = col_logical(),
  RecipientEmail = col_logical(),
  ExternalReference = col_logical(),
  LocationLatitude = col_double(),
  LocationLongitude = col_double(),
  DistributionChannel = col_character(),
  UserLanguage = col_character(),
  Q1 = col_character()
)

Warning message:
In infer_data_types(data, surveyID) :
  The 'StartDate', 'EndDate' and 'RecordedDate' variables were converted without passing
a specific timezone. If you like to set these timestamps to your own timezone, please
visit https://www.qualtrics.com/support/survey-platform/getting-started/managing-your-account/
(under 'User Settings'). See https://api.qualtrics.com/docs/dates-and-times for more
information about how the Qualtrics API handles dates and times.
> names(x)
 [1] "StartDate"             "EndDate"               "Status"                "IPAddress"            
 [5] "Progress"              "Duration (in seconds)" "Finished"              "RecordedDate"         
 [9] "ResponseId"            "RecipientLastName"     "RecipientFirstName"    "RecipientEmail"       
[13] "ExternalReference"     "LocationLatitude"      "LocationLongitude"     "DistributionChannel"  
[17] "UserLanguage"          "Q1"                   
> 
> # Test fetch_survey with problem survey with > 8,000 columns
> x <- fetch_survey(surveyID = "SV_0e8PaZwHzTsTzZX", force_request = TRUE)
  |==============================================================================================================| 100%

-- Column specification ------------------------------------------------------------------------------------------------
cols(
  StartDate = col_datetime(format = ""),
  EndDate = col_datetime(format = ""),
  Status = col_character(),
  IPAddress = col_character(),
  Progress = col_double(),
  `Duration (in seconds)` = col_double(),
  Finished = col_logical(),
  RecordedDate = col_datetime(format = ""),
  ResponseId = col_character(),
  RecipientLastName = col_logical(),
  RecipientFirstName = col_logical(),
  RecipientEmail = col_logical(),
  ExternalReference = col_logical(),
  LocationLatitude = col_double(),
  LocationLongitude = col_double(),
  DistributionChannel = col_character(),
  UserLanguage = col_character(),
  `Age - Parent Topics` = col_logical(),
  `Age - Topics` = col_logical()
)

> names(x)
 [1] "StartDate"             "EndDate"               "Status"                "IPAddress"            
 [5] "Progress"              "Duration (in seconds)" "Finished"              "RecordedDate"         
 [9] "ResponseId"            "RecipientLastName"     "RecipientFirstName"    "RecipientEmail"       
[13] "ExternalReference"     "LocationLatitude"      "LocationLongitude"     "DistributionChannel"  
[17] "UserLanguage"          "Age - Parent Topics"   "Age - Topics"         
> 
> # Test the the survey has columns
> survey_questions("SV_0e8PaZwHzTsTzZX")
# A tibble: 45 x 4
   qid   qname       question                                                                                 force_resp
   <chr> <chr>       <chr>                                                                                    <lgl>     
 1 QID15 coderName   "Choose your name"                                                                       FALSE     
 2 QID1  Paper       "Choose the paper you want to work on (click on the box below to show options)"          FALSE     
 3 QID21 validation  "<span style=\"font-size:24px;\">Is this the paper you want to work on? </span>\n<div> ~ FALSE     
 4 QID3  studyNumber "<div><span style=\"font-size:19px;\"><span style=\"font-family: Calibri, sans-serif;\"~ TRUE      
 5 QID5  Multinatio~ "The data was collected"                                                                 TRUE      
 6 QID4  Country     "In which country was data collected?"                                                   TRUE      
 7 QID6  Design      "The design of  this study was"                                                          TRUE      
 8 QID7  Time        "The measurement of the dependent variable (DV) was"                                     TRUE      
 9 QID8  Occupation  "The listeners' occupation. \n<div><span style=\"font-size:11px;\">If you are not sure ~ TRUE      
10 QID23 Role        "The speakers' role"                                                                     TRUE      
# ... with 35 more rows

**Comment by avi-kluger** [comment]
Hi Julia,

I answered on GitHub.

There is no issue with the datacenter. I can read another survey on the same account.  I can share the API with you.

Best,

Avi
