### ISSUE TITLE
Use client_credentials grant type with this library

### ISSUE THREAD

**Issue by abhigampa123** [ropensci/qualtRics#209]
Hello, I am only getting started to work with Qulatrics API service. I have a question regarding the authentication .

Is it possible to use client_credentials grant type using this library to authenticate Qualtrics APIs? I am able to successfully get tokens using OAuth2.0, so if there is away I can utilize this and pass it on to the functions like all_surveys(), fetch_survey() etc., that'd be great.

Thanks in advance!

**Comment by juliasilge** [comment]
There are [two important credentials](https://docs.ropensci.org/qualtRics/#register-your-qualtrics-credentials) you need to authenticate with the Qualtrics API. These are your **API key** and **institution-specific base URL**. 

- The base URL you pass to the qualtRics package should either look like `yourdatacenterid.qualtrics.com` or like `yourorganizationid.yourdatacenterid.qualtrics.com`, without a scheme such as `https://`. The [Qualtrics API documentation](https://api.qualtrics.com/instructions/) explains how you can find your base URL.

- You can read about how to generate an API token in [this section of the Qualtrics API documentation](https://www.qualtrics.com/support/integrations/api-integration/overview/#GeneratingAnAPIToken). The [code that constructs requests](https://github.com/ropensci/qualtRics/blob/master/R/utils.R#L68-L77) currently only works with API tokens, not OAuth authentication, so building out support for that would involve some pretty significant changes to this R package.

**Comment by abhigampa123** [comment]
Thank you very much for the explanation!
