### ISSUE TITLE
Refactor URL creation functions

### ISSUE THREAD

**Issue by juliasilge** [ropensci/qualtRics#216]
We have built up quite a number of functions to build URLs (`create_distributions_url()`, `create_survey_url()`, etc etc etc)) and at this point it would make more sense to have one function for URL creation with a `switch` statement or similar.

**Comment by jmobrien** [comment]
Agree, and almost decided to add something like this to the introduction of `fetch_description()`, something like `generate_url([survey/mailinglist/distribution id], type)`? 

The current setup is my doing, I think it helped at the time but couldn't handle the new features without sprawl.  Don't know if I'll have time to hammer out a fix in the near future but if if I do I've already thought it through somewhat.

**Comment by juliasilge** [comment]
IMO the current setup predates me taking on the maintenance of this package honestly! I think you were using the pattern that already existed. 

It would be most welcome if you were able to work on this at some point. 👍

**Comment by jmobrien** [comment]
Basically that, yes.  Tweaked an ad-hoc URL building system to be more modular.  But there were only 3 modules then.  I'll see if I can get to it.

**Comment by juliasilge** [comment]
@kevintroy you mentioned you have some free time this week and might be interested in working on the qualtRics package. I think this issue would be very impactful and good to fix before adding new features.

**Comment by kevintroy** [comment]
@juliasilge I'll give it a try!

**Comment by jmobrien** [comment]
Heads up @kevintroy -- I just submitted a PR on this one (#225).  I already have history with the current fraken-code in need of a rework, so I figured it was better for me to just try to quickly tackle it rather than have others spend their time deciphering what really needs ripping out.  Hopefully the new approach will make everyone's work more straightforward in the future.
