### ISSUE TITLE
Change read_csv to use lazy = FALSE when reading in raw data

### ISSUE THREAD

**Issue by ekothe** [ropensci/qualtRics#235]
The default behaviour of read_csv has recently changed to set lazy = TRUE when reading in a csv. While this does have advantages for very large files, it locks the file meaning that there are errors when the qualtRics package tries to delete the temp file and if attempting to reimport the data without first restarting R (see https://docs.google.com/forms/d/e/1FAIpQLSf3IyATNS182HyNlLAldeZakQqLGNaFCcfp42roYN52SAGscg/viewform for a summary of the issues).

Setting lazy = FALSE returns read_csv to its previous behaviour.

**Comment by juliasilge** [comment]
The readr maintainers did decide to [switch back to eager reading](https://github.com/tidyverse/readr/blob/master/NEWS.md) based on folks' responses to that survey so I'm not sure if it's a good idea to start setting those arguments in qualtRics itself.

If you are having any problems with your files being locked, etc, go ahead and install the development version of readr for the new settings (or you could install back to the pre-2.0.0 CRAN version).

**Comment by ekothe** [comment]
Thanks for the update @juliasilge I'd missed that 👍

**Comment by juliasilge** [comment]
Let me know if you run into further problems! 🙌
