### ISSUE TITLE
Literal "NA" text entries become missing data

### ISSUE THREAD

**Issue by jmobrien** [ropensci/qualtRics#243]
When someone has entered "NA" into a text field in Qualtrics, upon downloading it through `fetch_survey()` it will become missing data.  The reason for this is the `type_convert` call inside `read_survey`: the  argument `na`  by default includes "NA" string (along with "").  At a minimum, we should make this argument explicit, similar to  what was done with the same argument for the `read_csv` call just above it.

**Comment by juliasilge** [comment]
Closed by #244

**Comment by jmobrien** [comment]
Adding one semi-related thing I happened to notice just after.  Because the default for 1`trim_ws` is `TRUE`, blank entries (just spaces) also get turned into `NA`s.  We should probably not have trimming be the  default behavior, because Qualtrics itself won't treat that as missing/empty (e.g., if a survey is configured to reference a text field in conditional display logic).
