### ISSUE TITLE
Fetching shared surveys

### ISSUE THREAD

**Issue by JeffreyRStevens** [ropensci/qualtRics#246]
When I try to fetch a survey owned by someone at another organization and shared with me, I receive an error (fetching surveys that I own are fine, so it shouldn't be a base URL problem).
```
> fetch_survey("SV_????????")
Error: Qualtrics API raised a bad request (400) error - Please report this on
https://github.com/ropensci/qualtRics/issues
Run `rlang::last_error()` to see where the error occurred.
```
Is it possible to fetch shared surveys? I saw a similar issue in #234 with a reference to shared surveys but did not see if/how @avi-kluger solved the issue.

**Comment by juliasilge** [comment]
From my understanding of the docs on [collaboration](https://www.qualtrics.com/support/survey-platform/my-projects/sharing-a-project/) and the Qualtrics API, you will need to use the _other_ organization's base URL and an API key from the _other_ organization to access any of their surveys via API. I don't believe you can use your organization's base URL or API key for this.

If you'd like to get some clarification on this or advice on how to proceed, I'd recommend posting on [Qualtrics' API discussion section](https://www.qualtrics.com/community/categories/qualtrics-api-developer-corner) and also reach out to [support](https://www.qualtrics.com/support/).

**Comment by JeffreyRStevens** [comment]
Many thanks, @juliasilge. It looks like someone has asked this question in the API discussion section, but it hasn't been answered: https://community.qualtrics.com/XMcommunity/discussion/9671/access-responses-from-shared-survey.

**Comment by juliasilge** [comment]
Let us know if you have further questions! 🙌
