### ISSUE TITLE
Qualtrics update on 6/1/2022 will break fetch_distributions()

### ISSUE THREAD

**Issue by chrisumphlett** [ropensci/qualtRics#249]
Our org got an email about two changes to the List Distributions endpoint (https://github.com/ropensci/qualtRics/blob/master/R/fetch_distributions.R) which is used in the `fetch_distributions()` function in `qualtRics`.

The first change is to how pagination works, and I believe that no change will be required because we already use `nextPage`.

The second change will remove some fields that are currently mapped to columns in the resulting data.frame. I have not personally used the affected columns and do not believe it's necessary right now to make the connections to other endpoints that the email describes.

Is there a standard way to manage something like this in GH, where the work can be done in advance but it shouldn't be merged in?

Columns changing: 
![image](https://user-images.githubusercontent.com/7210482/149378956-6399f304-ac2e-4d29-bff2-bbef18156b22.png)

The entire email:
![image](https://user-images.githubusercontent.com/7210482/149379107-55110891-17a0-45b4-aa1b-c698763d0c65.png)

**Comment by juliasilge** [comment]
Thank you for sharing this! I think the best thing to do is to create a [draft PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) with the needed changes and leave it as draft until we are really there at needing to be merged in.

**Comment by juliasilge** [comment]
Closed in #250
