### ISSUE TITLE
Filter surveys before exporting with all_surveys()? Slow run time with many surveys.

### ISSUE THREAD

**Issue by manonironside** [ropensci/qualtRics#254]
Is there any way to filter which surveys are exported _before_ the `fetch_survey()` command? I find that `all_surveys()` takes a relatively long time to run when exporting from an account that contains many surveys, and this seems inefficient when I only need to use a few surveys.

**Comment by juliasilge** [comment]
I am guessing that you already understand that you can get the survey ID in different ways, such as from the web interface to Qualtrics. You don't need to use `all_surveys()` if you know the IDs (like `SV_3gtKaK8G1Zxxxxx`).

If you specifically are asking about getting these IDs from R only, that [uses the `/surveys` endpoint](https://api.qualtrics.com/api-reference/b3A6NjExMTQ-list-surveys). If I am reading that API documentation correctly, there's no real filtering ability, for example to find surveys with certain titles or anything like that.

**Comment by manonironside** [comment]
Ahh, yes - thanks for clarifying! I thought I had been getting an error with `fetch_survey()` when `all_surveys()` was not run first, but this is actually not the case.
