### ISSUE TITLE
give a little more guidance in setting base URL

### ISSUE THREAD

**Issue by jeanetteclark** [ropensci/qualtRics#257]
Loving the package, thank you for your hard work!

Based on my own experience setting up my credentials, and a flurry of related issues (#173, #179, #177, #184, #193), I think that it might be a nice improvement if `assert_base_url` does a little more checking to help guide users to the correct URL structure.

an  `assert_that` the URL does not start with `https://` statement would be the most helpful, and perhaps mention of no trailing slash in the existing statement for `endsWith` may also be useful.

I can make a quick PR if this is of interest

**Comment by juliasilge** [comment]
Closed in #258
