### ISSUE TITLE
Proposal: get rid of assertthat and replace with unified argument checking/adapting framework w/rlang

### ISSUE THREAD

**Issue by jmobrien** [ropensci/qualtRics#262]
So, I'm trying to finish adding a couple of the really essential features like filtering (#223), time/date control (#158), and survey activation/deactivation (#215, since that's not much extra work once we have date/times going).  

It's all pretty straightforward overall, but I keep running into how complicated our current handling of argument checking is making this.  Right now:

* Argument checks are all done by separate functions made using `assertthat`, (in assertions.R).  
* Generally, each argument (and even each thing to check for each argument), has its own custom-built `assert_*` function.  
* (Most) arguments are actually checked in a separate function (in utils.R) that goes through a list populated with arguments. 
* Those checks work okay, but they're still limited, because some (often optional) arguments can be specified in ways that still need further processing in order to match, say, the API protocol.  
* Any further processing of argument content, if needed, happens somewhere else entirely--for instance inside `construct_raw_payload.R`

`asserthat` is dead--it's not been updated in 5 years.  There are other good options like `checkmate`, but really as some of the recent updates have shown, `rlang::abort()` does quite well.  Also it seems evident that any further development of this kind of thing from the hadley/tidyverse is coming from there (e.g., https://github.com/r-lib/rlang/issues/1111).  

So, maybe continuing with `rlang` might make sense. But more generally while I'm trying to finish all this I was wondering if people wouldn't mind me reworking things more generally into streamlined approach that handles both cleaning and checking arguments in a unified way.  It's probably more efficient for what I'm doing right now and would make everyone's efforts easier going forward.  Thoughts?  If people don't hate the idea I'll send a draft in shortly, and can adjust the strategy from there.

**Comment by juliasilge** [comment]
Oh, I think it would be _GREAT_ if you reworked all that asserting and checking! I think it would be a huge improvement.

**Comment by jmobrien** [comment]
Okay, I'm working on it.  BTW, how do you feel about using the new native pipes (|>)?  It's a lot faster to write with them, but I wanted to run it by you first.

**Comment by jmobrien** [comment]
Glad that it helped.   Closing this, but feel free to reopen if there's more to do.
