### ISSUE TITLE
Adjust response caching to consider all differences in API request params?

### ISSUE THREAD

**Issue by jmobrien** [ropensci/qualtRics#300]
@juliasilge, thinking about #298--regardless of whether caching is relevant to that issue, caching itself is quite old, and predating a number of query-customization features.  It's now easy to imagine ways that a cached response download could preempt a novel API call to `fetch_survey()`, even though that new call is actually asking for something quite different from what's cached. 

Should this be fixed?  Maybe by changing the IDs for cached files to include other arguments?  Additionally or instead, perhaps by making `force_request = FALSE` the default?

**Comment by juliasilge** [comment]
I think the caching is quite surprising to most people, honestly, and changing the default would be a good way to go. I think that the caching can be a source of confusion and I don't know that it aligns with folks' expectations of how this function acts.

**Comment by jmobrien** [comment]
I avoid using it, myself, so I agree.  Plus, it would remove the situation where response data (and thus, potentially, PII) becomes saved to disk in a not-directly-specified locale (the temp folder).  

Would this qualify as a breaking change that we'd need to handle differently in publication?

**Comment by juliasilge** [comment]
Unfortunately there's not a great way to give messages to users when you change a default. Take a [look at these options](https://lifecycle.r-lib.org/articles/communicate.html#arguments). We could do a message for everyone who uses the function ever, but that is very noisy.

One option we have is to change the default and document the heck out of it, but not add messages.

Another option that might be good to consider is to turn _off_ the ability to cache altogether and [deprecate the argument like this](https://lifecycle.r-lib.org/articles/communicate.html#deprecating-an-argument-providing-a-new-default). This would give messages to anyone who passes in any value for `force_request`. Another option along those lines is to make a new argument for caching that replaces the old one, with the new one having the new default.

**Comment by juliasilge** [comment]
> So maybe I'm leaning to the "remove caching entirely" option? My guess is that will be fine-to-welcome overall. If enough users later express problems with the change, we can put it back in under a new argument--perhaps with things like precise request matching and user control over where caches (and their potential PII) are saved?

I like this plan a lot; it aligns with my own experience using the package and what we heard about most. 👍
