### ISSUE TITLE
Add thank you to README

### ISSUE THREAD

**Issue by JasperHG90** [ropensci/qualtRics#31]

**Comment by juliasilge** [comment]
@JasperHG90 Should the people who were thanked be added as `ctb`, i.e. did they write a fair amount of code? I saw some of them listed in individual `.R` files as authors? In R packages, it's more typical to give attribution through the `DESCRIPTION` file rather thanking in the README, although of course the amount of code that results in `ctb` status varies from package to package, from maintainer to maintainer.

**Comment by JasperHG90** [comment]
I'm fine with changing this. I wasn't sure how to do this at the time.
