### ISSUE TITLE
.sav/SPSS file type

### ISSUE THREAD

**Issue by MeganMcAuliffe** [ropensci/qualtRics#310]
Hello, I have been successful in downloading data from qualtrics using this package, however I am at a loss on how to obtain .sav/SPSS style formatting for variable attributes when a variable has a level to it these levels do not appear. Is there something I can change to import this style of file?

**Comment by juliasilge** [comment]
I may not be understand correctly your problem entirely, but have you tried using [haven](https://haven.tidyverse.org/) to save your dataset in a format for SPSS? Your workflow would be to import your Qualtrics data using this package, and then save using haven for a file format to open in SPSS.

If you don't want to use SPSS per se but you are trying to save on disk the factor levels, you may be better served saving your dataset as a [Parquet](https://arrow.apache.org/docs/r/reference/write_parquet.html) file.

**Comment by jmobrien** [comment]
Hi @MeganMcAuliffe, following up on this--did @juliasilge answer your question adequately?  

SPSS response downloads do contain some additional metadata about questions that the open format we use (.csv) does not fully contain.  Specifically, what's missing is complete information about the response options, including how many there are, their display labels, and their recoded values.  

We recognize that's valuable, especially for situations where having a clear, auditable record of procedures is an expected standard (e.g., academic research).  So we're working on it.  There are a couple of different ways we might incorporate that, but for various reasons it's more challenging than you might think.

@juliasilge as a side note, similar to saving .qsf's I suppose we could add a means to download .sav (SPSS) files?  If our central purpose is facilitating API access, it seems like that would be on-mission.  And not that hard--it could mostly re-use the `fetch_survey()` code.

**Comment by MeganMcAuliffe** [comment]
Thank you both for the information. I ended up using a combination of your package and the HTTR package. My code has a lot more but I singled out this section where I grabbed the spss file from. Hopefully this will be helpful for anyone else looking to do this. I use the qualtRics package to grab the available survey ID's which I then put into a URL for the POST call.

```
library(qualtRics)
library(svDialogs)
library(httr)

#individual token needs to be entered in the section on line 6 and 7
token_individual = "TOKEN"
qualtrics_api_credentials(api_key = "TOKEN",
                          base_url = "lucid.co1.qualtrics.com",
                          install = TRUE, overwrite=TRUE)
readRenviron("~/.Renviron")



#using qualtrics package to find survey id from survey name
surveys      <- all_surveys()
sfnumber     <- dlgInput("sfnumber")$res  #identifier number in survey name we use
survey_index <- grep(sfnumber,surveys$name)
surveyID     <- surveys$id[survey_index]


###This section uses POST command to grab SPSS File
url <- paste0("iad1.qualtrics.com/API/v3/surveys/",surveyID,"/export-responses")
token <- token_individual
data <- list("format" = "spss",
             "seenUnansweredRecode" = -99,
             "multiselectSeenUnansweredRecode" = 0,
             "useLabels" = FALSE,
             "includeDisplayOrder" = FALSE,
             "timeZone" = "America/Denver")
response <- POST(url, 
                 body = data,
                 encode = "json",
                 add_headers(`X-API-TOKEN` = token, 
                             `Content-Type` = "application/json"))
content(response)
saved <- content(response)
saved$result$status


#If the qualtrics project name has special characters it can break pulling the project
if (grepl("200",saved$meta$httpStatus) != TRUE){
  askYesNo("There is a bad character in your qualtrics project name please fix then run again.")
  stop()
}


#loop until results are complete
for (i in 1:100){
  
  get <- GET(paste0("iad1.qualtrics.com/API/v3/surveys/",surveyidqual,"/export-responses/",saved$result$progressId),
             add_headers(`X-API-TOKEN` = token))
  content(get)
  saved_get <- content(get)
  
  Sys.sleep(1)
  if(saved_get$result$status == "complete"){break}
  
  print(i)
  print(saved_get$result$status)
  
}




get2 <- GET(paste0("iad1.qualtrics.com/API/v3/surveys/",surveyidqual,"/export-responses/",saved_get$result$fileId,"/file"),
            add_headers(
              `Content-Type` = "application/json",
              `X-API-TOKEN` = token
            )
)


#write data to zip and then extract
bin <- content(get2, "raw")
writeBin(bin, "temp.zip")
Sys.sleep(5)
unzip("temp.zip")
Sys.sleep(5)
file.remove("temp.zip")

```

**Comment by juliasilge** [comment]
Thanks @MeganMcAuliffe! 🙌 

Let's close this issue for now but consider whether in the future we want to support direct downloading of an SPSS file.
