### ISSUE TITLE
exporting csv as numeric values

### ISSUE THREAD

**Issue by zaslove** [ropensci/qualtRics#312]
Hallo, 
This is not so much an issue but a question. I hope you don't mind me asking it here. First, I love the package. 

However, when I import the surveys from qualtrics  with  it seems to be using the export option from qualtrics as "use choice text". Or this is my interpretation. The variables in the columns are a combination of strings and numeric values. This is what happens in qualtrics if I use the option "use choice text". If I choose the option exporting as "numeric values", I don't get this issue. 

I first use: all_surveys() and then 

fetch_survey(surveys$id[52],           
                         start_date = "2023-01-25",
                         end_date = "2023-05-04",
                         label = T)

If this is not clear, I can show an example. But I thought I would first ask the question. 

Thanks in advance, 

Andrej

**Comment by jmobrien** [comment]
Hi @zaslove, 

The option `label` works equivalently to what you describe.  When `label = TRUE`, the downloaded data from `qualtRics` will be as if you selected "use choice text" in the web interface for downloads.  If `label = FALSE`, then it's equivalent to selecting "use numeric values".

Does that clear things up for you?  

I'm thinking it might be useful to be more explicit about that equivalence in the function documentation, or perhaps to rename the argument so it's more apparent.  We'll consider that.

**Comment by zaslove** [comment]
Hallo,
Many thanks! That helps. I thought it might have something to do with that option but was not sure. It might help t make it more clear. But in any case, a great package!

Best,

Andrej

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
