### ISSUE TITLE
Issue with fetching surveys

### ISSUE THREAD

**Issue by cbaumanis** [ropensci/qualtRics#320]
My qualtrics creds should be fine, since I've already used `qualtrics_api_credentials()` with install = TRUE to install my credentials to my .Renviron file.  The base URL I passed to the qualtRics package does look like yourdatacenterid.qualtrics.com or like yourorganizationid.yourdatacenterid.qualtrics.com, without a scheme such as https://

I'm able to grab all my surveys with `all_surveys()` and get the following (censored) result:
![image](https://github.com/ropensci/qualtRics/assets/40674446/52f21602-b7ac-4c74-b734-4a4d48bbab1c)

### My issue with fetch_survey()
But I cannot use `fetch_survey()` and I've tried using both the ID starting with SV_ and also like this 
`#grabbing first mode choice survey
mode1 <- fetch_survey(surveyID = surveys$id[1])`

And I get the following error:
_Error in `qualtrics_response_codes()`:
! Qualtrics API reported a bad request error (400):
* Please report this on https://github.com/ropensci/qualtRics/issues
Backtrace:
 1. qualtRics::fetch_survey(surveyID = surveys$id[1])
 2. qualtRics:::export_responses_request(...)
 3. qualtRics:::export_responses_init(surveyID = surveyID, body = body)
 4. qualtRics:::qualtrics_api_request(...)
 5. qualtRics:::qualtrics_response_codes(res)_

### Trying to run reprex() on my issue
I tried to use reprex() to see if I get an error, and if I did it right then what I got is an error that claims to crash R:
_This reprex appears to crash R. Call `reprex()` again with `std_out_err = TRUE` to get more info._

When I added `std_out_err = TRUE` to get more info, it says this:
_Error in xfun::normalize_path(path, ..., must_work = must_work, resolve_symlink = FALSE) : 
  unused argument (resolve_symlink = FALSE)_

**Comment by jmobrien** [comment]
Hard to know w/o more info, but as a next step have you confirmed that you have the correct content put in as your datacenter ID?  Some API endpoints are more forgiving than others about that.

Look here for more info on finding the right one for you: 
https://api.qualtrics.com/1aea264443797-base-url-and-datacenter-i-ds

As far as I know, these are the valid options:
"yul1" 
Canadian Data Center

"iad1" 
Washington, DC Area Data Center (previously CO1)

"sjc1" 
San Jose, California Data Center (previously AZ)

"fra1" 
European Union Data Center (previously EU2 or EU)

"lhr1" 
London, United Kingdom Data Center

"syd1" 
Sydney, Australia Data Center (previously AU1)

"sin1" 
Singapore Data Center

"hnd1" 
Tokyo, Japan Data Center

"gov1" 
US Government Data Center

**Comment by cbaumanis** [comment]
Oh wow. You nailed it. It was the datacenter ID that was messed up. It's all working fine now.

Thank you!

**Comment by juliasilge** [comment]
Let us know if you have further questions! 🙌
