### ISSUE TITLE
fetch distribution summary information?

### ISSUE THREAD

**Issue by chrischizinski** [ropensci/qualtRics#321]
Thanks for developing `qualtRics,` this package has become integral to my workflow. Is there a way to fetch the distribution summary for a given survey to collect individual-level information on who has responded to the survey or not?  I looked through the documentation and did not see anything stick out to me. 

Qualtrics allows you to do this by specifying the distribution mode and then providing a date range that you would like the information.  
![Screenshot 2023-08-06 at 11 36 28 AM](https://github.com/ropensci/qualtRics/assets/1197639/f4aafea5-612e-4a7c-8f88-467339fd5dc6)

**Comment by juliasilge** [comment]
I think what you are looking for is `fetch_distribution_history()`. Does that look right?

https://docs.ropensci.org/qualtRics/reference/fetch_distribution_history.html

**Comment by juliasilge** [comment]
Let us know if you have further questions! 🙌
