### ISSUE TITLE
error on fetching distribution history (i.e., full list of survey invitees along with distribution status)

### ISSUE THREAD

**Issue by g11217** [ropensci/qualtRics#322]
I'm getting such error when running  fetch_distribution_history.
Is this an issue with data size, or?  (~200-300k records)

fetch_distribution_history(surveylist$id[5])
Error: Qualtrics API reported a bad request error (400):

**Comment by jmobrien** [comment]
What's in `surveylist$id`?  This function would expect a distribution id (ex: "EMD_1234567890abcde"). 

If what you're passing is a list of survey ID's (that would start with "SV_"), then it could produce that error.

**Comment by g11217** [comment]
> What's in `surveylist$id`? This function would expect a distribution id (ex: "EMD_1234567890abcde").
> 
> If what you're passing is a list of survey ID's (that would start with "SV_"), then it could produce that error.

Thank you for this!  Yes, I need to use the specific distribution id, 

So, I ran fetch_distributions("survey ID") to get the list of distribution id's, to be used in fetch_distribution_history("dist ID")
Again, thank you for quick response

**Comment by jmobrien** [comment]
Glad that helped.
