### ISSUE TITLE
lag / incomplete pull of list_distribution_links() 

### ISSUE THREAD

**Issue by g11217** [ropensci/qualtRics#324]
Hello,

It seems qualtRics pulls distribution file in two parts,  fetch_distribution_history(), and list_distribution_links().
The main difference btw these two is that list_distribution_links() includes externalDataReference field (one of unique identifiers used for de-dup purpose).  I can join fetch_distribution_history() and list_distribution_links() by contactId.

The issue that I have is that list_distribution_links() does not pull all distribution records, > 48 hours past of 'sendDate' field in distribution ( fetch_distributions(  all_surveys()$id[n] ) ). e.g., I'm pulling 27570 distribution records and missing 108 (~0.4%).

So, the questions are
1) do you think this is some sort of lag in server sync (even > 48 hours)? If so, is there a way around this to create real-time call?
2) is there a way to call the complete distribution records in a single run (instead of running fetch_distribution_history(), and list_distribution_links(), sequentially, and call left_jon() )?

Thank you.

P.S., btw, huge fan of tidytext, and up-and-coming fan of qualtRics

**Comment by juliasilge** [comment]
Let us know if you have further questions! 🙌
