### ISSUE TITLE
feature discussion: custom temporary directory

### ISSUE THREAD

**Issue by jmobrien** [ropensci/qualtRics#325]
Thinking we should introduce some ability to specify custom temporary directory, and I'm wondering how to implement.  Couple options for this that I'm thinking about, and I'd love your thoughts @juliasilge (on the options and idea in general):

* adding a temporary directory argument to the api credentials function 
* adding in the use of R options (à la https://tibble.tidyverse.org/reference/tibble_options.html)
* adding (yet another!) argument to `fetch_survey()` and other functions for which this might be relevant (either instead of, or in addition to, the first two options.

Context: I've been talking w/some people whose new interest in using `qualtRics` is running up against explicit policies regarding where and how user data can be written to disk.  Now, changes in #317 improved user control on this front for `fetch_survey()` quite a bit; however, because R apparently offers no way to "unzip" a binary representation of a file held in memory, one disk write is still needed to produce a usable dataframe of responses.  While #317 did at least make it so the .zip file would generally only be there for few moments before being deleted, some users may also need to control where that .zip file goes.

**Comment by jmobrien** [comment]
Hmm.  My initial impression is that this seems right--let's not add more stuff unless we need to, nor reinvent the wheel when we can just write documentation pointing users to existing solutions.  

I'm having some doubts, though.  But before I get into anything, can you help me understand this proposed approach better?

For `withr::with_tempdir()`, is the idea that a user would just wrap that around a `qualtRics` function, like so?

``` r 
withr::with_tempdir(
   code = fetch_survey(surveyID), 
   tempdir = my_tempdir
)

```

I'm less clear about `withr::local_tempdir()` would be used--as part of users' custom function(s)?  At the top level, so something to add to a script/the beginning of an interactive session?  The latter seems like the easiest, but from some testing I'm not sure how it's supposed to be done.

**Comment by juliasilge** [comment]
I would use the "with" variant like this:

``` r
library(qualtRics)

out <- withr::with_tempdir(
  fetch_survey("SV_3gbwq8aJgqPwQDP"),
  tmpdir = "~/Downloads/"
)
#>   |                                                                              |                                                                      |   0%  |                                                                              |======================================================================| 100%
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   .default = col_character(),
#>   StartDate = col_datetime(format = ""),
#>   EndDate = col_datetime(format = ""),
#>   Progress = col_double(),
#>   `Duration (in seconds)` = col_double(),
#>   Finished = col_logical(),
#>   RecordedDate = col_datetime(format = ""),
#>   RecipientLastName = col_logical(),
#>   RecipientFirstName = col_logical(),
#>   RecipientEmail = col_logical(),
#>   ExternalReference = col_logical(),
#>   LocationLatitude = col_double(),
#>   LocationLongitude = col_double(),
#>   SolutionRevision = col_double()
#> )
#> ℹ Use `spec()` for the full column specifications.

out
#> # A tibble: 42 × 24
#>    StartDate           EndDate             Status         IPAddress     Progress
#>    <dttm>              <dttm>              <chr>          <chr>            <dbl>
#>  1 2020-02-19 18:16:42 2020-02-19 18:17:19 Survey Preview <NA>               100
#>  2 2020-02-19 18:30:55 2020-02-19 18:34:37 IP Address     98.14.36.23        100
#>  3 2020-02-19 18:49:48 2020-02-19 18:50:23 IP Address     75.82.50.44        100
#>  4 2020-02-19 19:46:41 2020-02-19 19:47:01 IP Address     75.172.11.120      100
#>  5 2020-02-19 19:56:28 2020-02-19 19:59:15 IP Address     194.59.251.2…      100
#>  6 2020-02-20 05:22:10 2020-02-20 05:22:58 IP Address     66.168.182.1…      100
#>  7 2020-02-20 05:31:28 2020-02-20 05:32:06 IP Address     35.138.90.71       100
#>  8 2020-02-20 05:52:59 2020-02-20 05:53:26 IP Address     24.254.16.188      100
#>  9 2020-02-20 10:09:48 2020-02-20 10:10:12 IP Address     99.88.198.1        100
#> 10 2020-02-20 19:52:01 2020-02-20 19:52:02 Survey Test    <NA>               100
#> # ℹ 32 more rows
#> # ℹ 19 more variables: `Duration (in seconds)` <dbl>, Finished <lgl>,
#> #   RecordedDate <dttm>, ResponseId <chr>, RecipientLastName <lgl>,
#> #   RecipientFirstName <lgl>, RecipientEmail <lgl>, ExternalReference <lgl>,
#> #   LocationLatitude <dbl>, LocationLongitude <dbl>, DistributionChannel <chr>,
#> #   UserLanguage <chr>, Q63 <ord>, Q16 <ord>, Q17 <chr>, Q18 <ord>, Q19 <chr>,
#> #   Q22 <chr>, SolutionRevision <dbl>
```

<sup>Created on 2023-08-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

You are right that the `local_*()` functions in withr work best within a function, although I think it's technically "when they reach the end of their scope". That would be more for folks who are using qualtRics functions within other custom functions. Maybe we can just document how to use `withr::with_tempdir()`.

**Comment by jmobrien** [comment]
Hmm, it looks like `with_tempdir()` doesn't seem to do what we first thought.  It just temporarily creates a folder to use as a working directory, then executes the code there.  For functions like `fetch_survey()` that explicitly write to the system-specified temporary directory, it does nothing.  

I think we have to do something more explicit to make this work.  Easy enough, though: we can just pass a `tempdir` arg to `fs::file_temp()`.  (@juliasilge never said thanks for that addition to #317, btw--really cleans things up).

Also, having thought about this, I think explicitly including temp directory control is something we should do anyway.  Legal and ethical standards mandating careful data management are the norm in many spheres that use human participant data--e.g. anything operating under an IRB, or FERPA, HIPPA, etc.  So, while I think you and I are both wary of feature bloat (in `fetch_survey()` especially), I think giving users explicit control of where human participants data goes is entirely on-mission for the package.
