### ISSUE TITLE
Future look: Funding support from Qualtrics?

### ISSUE THREAD

**Issue by sda030** [ropensci/qualtRics#328]
This is a bit on the side of the technical matters, but I find it odd that ropensci hosts this (nice) package while a multimillion-dollar company is not listed among the financial contributors (https://cran.r-project.org/web/packages/qualtRics/). Sure, open source projects might be harmed if no longer voluntary and there would need to be no string attached - but I think in this case everyone would benefit from it (package users, Qualtrics, maintainers)? 

P.S. I am not referring to myself as a recipient.

**Comment by juliasilge** [comment]
One way that Qualtrics the company does support the maintenance of this package is by giving me (the maintainer) a free Qualtrics account with pretty much everything (all features) turned on. Super glad to have that!

**Comment by sda030** [comment]
That's nice, though I think you deserve more. If they provided a month's salary you could perhaps attract more assistance from the other contributors? (I know you are busy yourself with Posit and sending me hex-stickers) ;) But seriously, I will plead with our customer care person to see if strings can be pulled.

**Comment by juliasilge** [comment]
Thanks for these kind words and let us know if you have further questions! 🙌
