### ISSUE TITLE
results from all_surveys() and list_surveys is different

### ISSUE THREAD

**Issue by vjbrady68** [ropensci/qualtRics#330]
Hi There! 

Any thoughts on why I would be getting a different number of results when I use all_surveys vs. list_surveys? The survey data I want to pull shows up when I use list_surveys() but not all_surveys and then when I go to use fetch_survey() I get a 404 error.

All_surveys() gives me 148 results and list_surveys() gives me 169. Not only is the number of surveys getting pulled different, they are different samples... 114 are the same across the two commands, but then they each have a set of surveys that is unique to that method. Am I doing something wrong or have a setting I need to change?

**Comment by jmobrien** [comment]
Sorry, I'm a bit confused--`list_surveys()` isn't a function in this package.  Are you perhaps using a different package, or someone's fork of this one?  

Or querying the API endpoint (which is named "list surveys") yourself somehow (e.g., via the [website](https://api.qualtrics.com/2c55b7ff8b0c7-list-surveys))?

**Comment by vjbrady68** [comment]
Ah yes, you are correct - list_surveys is from another package... I guess the question still stands though - what might cause there to be surveys that I'm the owner of that aren't getting pulled through with the all_surveys() call?

**Comment by jmobrien** [comment]
No clue without more info.  What's list_surveys from (I couldn't find it myself)?
  
Also, are there any common characteristics of the surveys you're seeing with the other method, but not here?  Any info/printouts you're willing to share here could be useful.

**Comment by juliasilge** [comment]
Tough for us to say what you may be experiencing from another package, but here in the qualtRics package, the `all_surveys()` function calls the `/surveys` endpoint using your authentication:
https://api.qualtrics.com/2c55b7ff8b0c7-list-surveys

You can see how the URL is built here:
https://github.com/ropensci/qualtRics/blob/9a943be9f05efef4d33f5a4fe9d038563d2db305/R/utils.R#L146

I suggest that you ask the other package maintainers how the other function works.

**Comment by vjbrady68** [comment]
It's from the [QualtricsInR package](https://github.com/ppssphysics/QualtricsInR). Ultimately though - the bigger issue here is that there are surveys that I am the owner of that aren't showing up in my all_surveys call and when I drop the survey id into the fetch_surveys command (even though I am the owner/creator of the survey) I end up with a 404 error. 

I need to do this analysis pretty quickly, so I think I'll just set this aside and export the results directly from Qualtrics as a CSV even though it's not ideal.

**Comment by juliasilge** [comment]
Let us know if you have further questions! 🙌
