### ISSUE TITLE
read_survey() no longer (or inconsistently) breaks out sets

### ISSUE THREAD

**Issue by isaacahuvia** [ropensci/qualtRics#344]
In the past, I've found that `read_survey()` automatically breaks out sets from "select-all-that-apply"-type questions. This is the same behavior that you get with `fetch_survey()` with `breakout_sets = T`. However, with some recent update that seems to no longer be the case. Now when I run `read_survey()` with qualtRics version 3.2.0 and readr version 2.1.5 I'm left with multiple responses separated by commas within the same column.

I noticed this old issue (https://github.com/ropensci/qualtRics/issues/210) and can confirm that this current problem persists with both numeric and response label data.

Is it possible to restore this functionality to `read_survey()` (or maybe better yet, let users specify a `breakout_sets` option in that function like they can with `fetch_survey()`?

**Comment by juliasilge** [comment]
Thanks for your patience on this question @isaacahuvia!

Can you say a little more about how you are running your code and what you are seeing? I have [an example survey here](https://conjoint.qualtrics.com/jfe/form/SV_56icaa9YAafpAqx) here with a select-all-that-apply question, and when I use `fetch_survey()` I see the responses broken out into separate columns:

``` r
library(tidyverse)
library(qualtRics)

res <- fetch_survey("SV_56icaa9YAafpAqx")
#>   |                                                                              |                                                                      |   0%  |                                                                              |======================================================================| 100%
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   .default = col_character(),
#>   StartDate = col_datetime(format = ""),
#>   EndDate = col_datetime(format = ""),
#>   Progress = col_double(),
#>   `Duration (in seconds)` = col_double(),
#>   Finished = col_logical(),
#>   RecordedDate = col_datetime(format = ""),
#>   Q3.13 = col_double(),
#>   SolutionRevision = col_double(),
#>   `Q3.8 - Parent Topics` = col_logical(),
#>   `Q3.8 - Sentiment Polarity` = col_double(),
#>   `Q3.8 - Sentiment Score` = col_double(),
#>   `Q3.8 - Topic Sentiment Label` = col_logical(),
#>   `Q3.8 - Topic Sentiment Score` = col_logical()
#> )
#> ℹ Use `spec()` for the full column specifications.
```

``` r
res |> 
  select(contains("Q35"))
#> # A tibble: 44 × 4
#>    Q35_1        Q35_2       Q35_7 Q35_7_TEXT                       
#>    <chr>        <chr>       <chr> <chr>                            
#>  1 Ropes Course Trust Falls Other <NA>                             
#>  2 Ropes Course <NA>        <NA>  <NA>                             
#>  3 Ropes Course <NA>        <NA>  <NA>                             
#>  4 Ropes Course <NA>        <NA>  <NA>                             
#>  5 Ropes Course <NA>        <NA>  <NA>                             
#>  6 Ropes Course <NA>        <NA>  <NA>                             
#>  7 <NA>         <NA>        Other communal salami and catnip frenzy
#>  8 <NA>         <NA>        Other Staying inside alone             
#>  9 <NA>         <NA>        Other Spa day                          
#> 10 <NA>         <NA>        Other lil more salami                  
#> # ℹ 34 more rows
```

<sup>Created on 2024-06-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

This is with qualtRics 3.2.0 and readr 2.1.5. Can you share more detail about what you are seeing?

**Comment by isaacahuvia** [comment]
Thank you for your response! This still works with `fetch_survey()`, but it doesn't seem to work with `read_survey()`. If you export your data from Qualtrics to .csv and then read it with `read_survey()`, maybe you'll see what I mean?

We would simply use `fetch_survey()` for our purposes, but our organization doesn't pay for Qualtrics' API capabilities, so we're stuck reading things from .csv.

**Comment by juliasilge** [comment]
Ah OK, I understand now! I totally glossed over where you said `read_survey()` earlier.

This is coming from Qualtrics itself, in terms of how they create a CSV for downloading. Since `read_survey()` doesn't use the API at all, the only way to get the information about sets is from the CSV itself, which is why we end up in this situation. If you know which column contains sets, you can use tidyr functions yourself to break them out into separate columns. I think this might be the most straightforward approach:

``` r
library(tidyverse)
library(qualtRics)
res <- read_survey("~/Downloads/Cats Can Have a Little Salami_June 22, 2024_09.27.csv")
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   .default = col_character(),
#>   StartDate = col_datetime(format = ""),
#>   EndDate = col_datetime(format = ""),
#>   Progress = col_double(),
#>   `Duration (in seconds)` = col_double(),
#>   Finished = col_logical(),
#>   RecordedDate = col_datetime(format = ""),
#>   Q3.13 = col_double(),
#>   SolutionRevision = col_double(),
#>   `Q3.8 - Parent Topics` = col_logical(),
#>   `Q3.8 - Sentiment Polarity` = col_double(),
#>   `Q3.8 - Sentiment Score` = col_double(),
#>   `Q3.8 - Topic Sentiment Label` = col_logical(),
#>   `Q3.8 - Topic Sentiment Score` = col_logical()
#> )
#> ℹ Use `spec()` for the full column specifications.
```

``` r

res |> 
  separate_rows(Q35, sep = ",") |> 
  pivot_wider(names_from = Q35, values_from = Q35) |> 
  rename(Q35_1 = `Ropes Course`, Q35_2 = `Trust Falls`, Q35_7 = Other) |> 
  select(-`NA`) |> 
  select(contains("Q35"))
#> # A tibble: 44 × 4
#>    Q35_7_TEXT                        Q35_1        Q35_2       Q35_7
#>    <chr>                             <chr>        <chr>       <chr>
#>  1 <NA>                              Ropes Course Trust Falls Other
#>  2 <NA>                              Ropes Course <NA>        <NA> 
#>  3 <NA>                              Ropes Course <NA>        <NA> 
#>  4 <NA>                              Ropes Course <NA>        <NA> 
#>  5 <NA>                              Ropes Course <NA>        <NA> 
#>  6 <NA>                              Ropes Course <NA>        <NA> 
#>  7 communal salami and catnip frenzy <NA>         <NA>        Other
#>  8 Staying inside alone              <NA>         <NA>        Other
#>  9 Spa day                           <NA>         <NA>        Other
#> 10 lil more salami                   <NA>         <NA>        Other
#> # ℹ 34 more rows
```

<sup>Created on 2024-06-22 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

With only the CSV itself, I don't believe that we can create robust handling of sets when we are doing `read_survey()`.

**Comment by isaacahuvia** [comment]
Got it, thanks! Do you use the API to get information about column types, too, then? (i.e., information that is lost in the .csv format)?

**Comment by juliasilge** [comment]
Yep, that is correct. 👍

**Comment by isaacahuvia** [comment]
Got it. For some reason, I remember experiencing `read_survey()` breaking out sets with .csv's in the past. But thank you - I'll close this issue!
