### ISSUE TITLE
Parsing Failures in getSurveys

### ISSUE THREAD

**Issue by bradydehart** [ropensci/qualtRics#76]
Hello,

 Since to update in February and the incorporation of readr, I frequently get parsing failures when importing data using the numeric values instead of the labels. This issue did not occur before the update.  I have included a screengrab (with personal and IRB related info edited out). This appears to be a similar problem as was previously posted. However, when I set useLabels to FALSE and convertvariables to FALSE in the registerOptions command, it does not resolve the issue. Thank you for your help and wonderful package!
![error](https://user-images.githubusercontent.com/32200810/39636179-7c1606b4-4f8d-11e8-9a87-c821eae36b80.png)

**Comment by JasperHG90** [comment]
Hi Brady,

Thanks for your message and my apologies for this late response. I'm currently working on a project and I don't have a lot of time to spend on this project. There will be an update soon (-ish) (+- 2 months) that will address this and other issues. Given that you are running into issues, could I ask you if you are available for testing out updates once I get around to them?

Thanks!

Jasper.

**Comment by bradydehart** [comment]
I would be happy to test. Thanks!

Brady

**Comment by Lingtax** [comment]
Just wanting to 👍 this issue and volunteer for testing.

**Comment by juliasilge** [comment]
Hello there, all! 👋 I am the new maintainer of this package, and I'd love to get to the bottom of some of these issues with `read_survey()`. If you are able, can you re-install from GitHub here, run the following code, and then email me (my address is in the DESCRIPTION file) the CSV file at the path you find? It will be a fairly raw, unprocessed CSV file, but that is the one that is causing problems, apparently!

```
root_url <- qualtRics:::append_root_url(Sys.getenv("QUALTRICS_BASE_URL"), "responseexports")
raw_payload <- qualtRics:::create_raw_payload(
    surveyID = <YOUR SURVEY ID HERE>,
    label = TRUE,
    last_response = NULL,
    start_date = NULL,
    end_date = NULL,
    unanswer_recode = NULL,
    limit = NULL,
    local_time = FALSE,
    include_questions = NULL
  )
res <- qualtRics:::qualtrics_api_request("POST", url = root_url, body = raw_payload)
ID <- res$result$id
survey.fpath <- qualtRics:::download_qualtrics_export(paste0(root_url, ID), verbose = TRUE)
survey.fpath
```

**Comment by juliasilge** [comment]
Thanks so much for this report! If you use qualtRics again and have problems, please do open a new issue.
