### ISSUE TITLE
readSurvey returns error with exported qualtrics data

### ISSUE THREAD

**Issue by tleisman** [ropensci/qualtRics#81]
When I try to use readSurvey to input raw data from certain surveys using an exported .csv (directly from Qualtrics), R returns a warning and does not input the data. 

I attempt to run this code: 
df <- readSurvey("C:\\Users\\leismant\\Downloads\\test survey data.csv")

And I get: 
Warning: 101 parsing failures.
row # A tibble: 5 x 5 col     row col   expected   actual     file       expected   <int> <chr> <chr>      <chr>      <chr>      actual 1     2 NA    58 columns 80 columns "'C:\\Use~ file 2     3 NA    58 columns 80 columns "'C:\\Use~ row 3     4 NA    58 columns 80 columns "'C:\\Use~ col 4     5 NA    58 columns 80 columns "'C:\\Use~ expected 5     6 NA    58 columns 80 columns "'C:\\Use~
... ................................. ... .............................................. ........ ........................................................ [... truncated]
Error in names(rawdata) <- names(header) : 
  'names' attribute [80] must be the same length as the vector [58]
In addition: Warning messages:
1: In rbind(names(probs), probs_f) :
  number of columns of result is not a multiple of vector length (arg 1)
2: Duplicated column names deduplicated: 'StartDate' => 'StartDate_1' [66], 'RecipientFirstName' => 'RecipientFirstName_1' [78], 'RecipientLastName' => 'RecipientLastName_1' [79] 

We've encountered this problem with many of our surveys and are having trouble determining the difference between the cases when it works and when it doesn't. I haven't been able to prepare a de-identified example of the "success case" but if that's necessary I can do so.

This may be the wrong place to submit this issue - not sure if it's a "bug" or just user error.

**Comment by HarrisonBP** [comment]
It seems like I'm having the same issue:

`T2_SCENARIO <- qualtRics::readSurvey("T2Scenario_September 23, 2018_11.51.csv", legacyFormat = FALSE)`

Warning: 2 parsing failures.
row # A tibble: 2 x 5 col     row col   expected   actual     file                                                       expected   <int> <chr> <chr>      <chr>      <chr>                                                      actual 1     2 NA    30 columns 75 columns 'T2 - Scenario/T2 - Scenario_September 23, 2018_11.51.csv' file 2     3 NA    30 columns 75 columns 'T2 - Scenario/T2 - Scenario_September 23, 2018_11.51.csv'

Error in names(rawdata) <- names(header) : 
  'names' attribute [75] must be the same length as the vector [30]

However, if I load data from the legacy downloader:

`T2_SCENARIO <- qualtRics::readSurvey("T2__Scenario.csv", legacyFormat = TRUE)`

Warning message:
Missing column names filled in: 'X104' [104] 

However, the csv only contains 103 columns.

Which gave me the idea to use the non-legacy format and enable "Remove line breaks" in more options. This is a good workaround for now - it works anyway.

**Comment by juliasilge** [comment]
Hello there, all! 👋 I am the new maintainer of this package, and I'd love to get to the bottom of some of these issues with `read_survey()`. If you are able, can you re-install from GitHub here, run the following code, and then email me (my address is in the DESCRIPTION file) the CSV file at the path you find? It will be a fairly raw, unprocessed CSV file, but that is the one that is causing problems, apparently!

```
root_url <- qualtRics:::append_root_url(Sys.getenv("QUALTRICS_BASE_URL"), "responseexports")
raw_payload <- qualtRics:::create_raw_payload(
    surveyID = <YOUR SURVEY ID HERE>,
    label = TRUE,
    last_response = NULL,
    start_date = NULL,
    end_date = NULL,
    unanswer_recode = NULL,
    limit = NULL,
    local_time = FALSE,
    include_questions = NULL
  )
res <- qualtRics:::qualtrics_api_request("POST", url = root_url, body = raw_payload)
ID <- res$result$id
survey.fpath <- qualtRics:::download_qualtrics_export(paste0(root_url, ID), verbose = TRUE)
survey.fpath
```

**Comment by juliasilge** [comment]
Thanks so much for this report! If you use qualtRics again and have problems, please do open a new issue.
