### ISSUE TITLE
Downloading in progress responses

### ISSUE THREAD

**Issue by adinneen** [ropensci/qualtRics#84]
I need to be able to download in-progress responses from my qualtrics survey.  Is there a way to do that with the current package? If not, can this be added.  Additionally can this package be set to pull in any stored values from qualtrics including those passed through via another site.

**Comment by juliasilge** [comment]
Hello there @adinneen! I am the new maintainer of this package. It does look like the API we use in this package does not support downloading in-progress, partial responses; this is a decision on the part of Qualtrics, not this R package.

As far as stored values, yep, those should be accessible! I have done this just like @ryantsullivan mentioned, as embedded data.
