### ISSUE TITLE
package ‘qualtRics’ is not available (for R version 3.5.1)

### ISSUE THREAD

**Issue by andre-rabelo** [ropensci/qualtRics#88]
Trying to install the 'qualtRics' package with "install.packages("qualtRics")" on RStudio, but got the following error message: package ‘qualtRics’ is not available (for R version 3.5.1). I also attempted "devtools::install_github("ropensci/qualtRics")" but got the following error message: ERROR: lazy loading failed for package 'qualtRics'
* removing 'C:/Users/andre_rabelo/Documents/R/win-library/3.5/qualtRics'
* restoring previous 'C:/Users/andre_rabelo/Documents/R/win-library/3.5/qualtRics'
In R CMD INSTALL
Installation failed: Command failed (1)

Here is some useful info: 
R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

Any advice on how to deal with this is welcome!

Best,

André

**Comment by JasperHG90** [comment]
Hi Andre,

the qualtRics package was removed from CRAN but will be re-submitted this week.

Best,

Jasper.
