### ISSUE TITLE
getSurvey(): number of decimals for LocationLatitude and LocationLongitude variables

### ISSUE THREAD

**Issue by awcm0n** [ropensci/qualtRics#90]
My survey contains latitude and longitude data that appear to be rounded to 1 decimal during import (34.1004943847656 -> 34.1; -118.325401306152 -> -118.3). Can this be avoided?

**Comment by juliasilge** [comment]
There is no rounding occurring during import, in the current version of the package. The type of object returned by `fetch_survey()` is a [tibble](https://r4ds.had.co.nz/tibbles.html), a special case of R's data frame. One of the special characteristics of tibbles is their print method, which only prints out a lower number of decimal places. The "real" number of decimal places is still stored by R (try printing out `my_survey$LocationLatitude`) but it isn't displayed, for convenience, when printing out all the columns.

Let me know if you have any questions on that!
