### ISSUE TITLE
readSurvey() "Error: The survey you are trying to import has no responses."

### ISSUE THREAD

**Issue by Scott123456** [ropensci/qualtRics#92]
I'm using getSurvey() in a loop to gather data from multiple surveys. If it gets to a survey with no responses, readSurvey() returns an error and terminates. Instead of using assert_that to check number of responses and error if 0, I would the function to return a warning, or nothing at all, or a data frame with 0 records. Then I can choose what contingency I want to perform.

**Comment by juliasilge** [comment]
I commented on your PR, @Scott123456, but one option I could see being acceptable is for `getSurvey()` to return a zero-row dataframe with a warning, instead of the current error. Thoughts?

**Comment by juliasilge** [comment]
Let me know if you have further thoughts on [using purrr::safely](https://r4ds.had.co.nz/iteration.html#dealing-with-failure) or the PR @Scott123456! I'm going to close this issue for now.
