### ISSUE TITLE
possible relicensing of qualtRics from GPL-3 to MIT

### ISSUE THREAD

**Issue by juliasilge** [ropensci/qualtRics#95]
@JasperHG90 I have some interest in changing the license on this package to MIT. I don't claim to an expert level knowledge of software licensing, but my understanding of their relative differences leads me to a preference for the more permissive MIT license. Would you be on board with such a license change? Was there a particular motivation behind the choice of GPL-3?

**Comment by JasperHG90** [comment]
Hi Julia. I don't have strong feelings about this. At the time, I chose GPL-3 because it forces developers who use the source code to make their code open-source, which I liked. I'm on board to change it if you want to.

**Comment by JasperHG90** [comment]
I approve changing the licens for the qualtRics R package from GPL-3 to MIT.

**Comment by juliasilge** [comment]
Turns out all copyright holders (contributors) need to agree to change the license. Very small changes like typos don't amount to someone being a copyright holder, but the following folks definitely need to be on board.

:question: @phoebewong 
:question: @samuelkaminsky 
:question: @eknud 

I'd like to change to a more permissive MIT license to make it easier for folks working in industry contexts to use this package and extend it in their work if necessary. Can you, in a comment on this issue, say something like, "I agree" or similar?

**Comment by samuelkaminsky** [comment]
I agree with the change to the MIT license.

**Comment by eknud** [comment]
I agree with the change as well.

**Comment by phoebewong** [comment]
I agree with the change.

**Comment by juliasilge** [comment]
Thank you, all! I appreciate your flexibility and responsiveness. Not to mention your work on this package! 🙌
