### ISSUE TITLE
Add contributors to DESCRIPTION

### ISSUE THREAD

**Issue by juliasilge** [ropensci/qualtRics#96]
There were a couple of folks who contributed code to this package previously who could be added as contributors (`ctb`) if they like. Unless you object/decline, would you submit a PR with yourself added as `ctb` to the [DESCRIPTION](https://github.com/ropensci/qualtRics/blob/master/DESCRIPTION) file?

:star:@phoebewong
:star:@samuelkaminsky 
:star:@eknud 

Thanks for your contributions to this package!

**Comment by samuelkaminsky** [comment]
Just added a PR for myself. Thanks Julia!
